### ISSUE TITLE
Problems with local take off using Gazebo.

### ISSUE THREAD

**Issue by revantad** [mavlink/mavros#1104]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

Take off service not working as expected for local take off.

### MAVROS version and platform

Mavros: ?0.18.4?
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[  ] ArduPilot
[x ] PX4

Version: 1.6.5

### Node logs

```
copy output of mavros_node. Usually console where you run roslaunch
```

### Diagnostics
```
header: 
  seq: 638
  stamp: 
    secs: 1540220833
    nsecs: 367693214
  frame_id: ''
status: 
  - 
    level: 0
    name: "mavros: FCU connection"
    message: "connected"
    hardware_id: "tcp://127.0.0.1:5760"
    values: 
      - 
        key: "Received packets:"
        value: "38570"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "194"
      - 
        key: "Tx sequence number:"
        value: "113"
      - 
        key: "Rx total bytes:"
        value: "16606347"
      - 
        key: "Tx total bytes:"
        value: "105988"
      - 
        key: "Rx speed:"
        value: "59024.000000"
      - 
        key: "Tx speed:"
        value: "375.000000"
  - 
    level: 2
    name: "mavros: GPS"
    message: "No satellites"
    hardware_id: "tcp://127.0.0.1:5760"
    values: 
      - 
        key: "Satellites visible"
        value: "0"
      - 
        key: "Fix type"
        value: "0"
      - 
        key: "EPH (m)"
        value: "Unknown"
      - 
        key: "EPV (m)"
        value: "Unknown"
  - 
    level: 0
    name: "mavros: Heartbeat"
    message: "Normal"
    hardware_id: "tcp://127.0.0.1:5760"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "416"
      - 
        key: "Frequency (Hz)"
        value: "0.962945"
      - 
        key: "Vehicle type"
        value: "Quadrotor"
      - 
        key: "Autopilot type"
        value: "PX4 Autopilot"
      - 
        key: "Mode"
        value: "MANUAL"
      - 
        key: "System status"
        value: "Standby"
  - 
    level: 0
    name: "mavros: System"
    message: "Normal"
    hardware_id: "tcp://127.0.0.1:5760"
    values: 
      - 
        key: "Sensor present"
        value: "0x00000000"
      - 
        key: "Sensor enabled"
        value: "0x00000000"
      - 
        key: "Sensor helth"
        value: "0x00000000"
      - 
        key: "CPU Load (%)"
        value: "42.8"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 0
    name: "mavros: Battery"
    message: "Normal"
    hardware_id: "tcp://127.0.0.1:5760"
    values: 
      - 
        key: "Voltage"
        value: "12.10"
      - 
        key: "Current"
        value: "0.0"
      - 
        key: "Remaining"
        value: "97.0"
```

### Check ID

```
WARNING: mavros/target_system_id not set. Used default value: 1
WARNING: mavros/target_component_id not set. Used default value: 1
NOTE: Target parameters may be unset, but that may be result of incorrect --mavros-ns option.Double check results!
OK. I got messages from 1:1.

---
Received 3682 messages, from 2 addresses
sys:comp   list of messages
  0:0     655617
  1:1     0, 1, 83, 36, 105, 266, 140, 2, 77, 111, 76, 147, 245, 74

```
