### ISSUE TITLE
No definition of [x] for OS [debian]

### ISSUE THREAD

**Issue by grcasanova** [mavlink/mavros#1132]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details
Mavros installation on rosbot image for Raspberry Pi 3 B, command 
`rosdep install --from-paths src --ignore-src -y` fails with

> ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> image_geometry: No definition of [opencv3] for OS [debian]
> mavros: No definition of [geographic_msgs] for OS [debian]
> mavros_msgs: No definition of [geographic_msgs] for OS [debian]
> mavros_extras: No definition of [tf] for OS [debian]
> test_mavros: No definition of [control_toolbox] for OS [debian]
> cv_bridge: No definition of [opencv3] for OS [debian]

### MAVROS version and platform

Mavros: 0.18.4
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[x] ArduPilot
[  ] PX4

Version: 3.7.1

**Comment by vooon** [comment]
That happens because rosdep repo don't have entries for `[x]`.
You can:
a) override OS distro
b) add path local rosdep yaml to /etc, then write file like that:
```yaml
#$ cat local_rosdep.yaml 
#libvtk:
#  ubuntu:
#    saucy: [libvtk5-dev]
#libflann:
#  ubuntu:
#    saucy: [libflann-dev]
#libglew-dev:
#  ubuntu:
#    saucy: [libglew-dev]
#gstreamer0.10-plugins-ugly:
#  ubuntu:
#    saucy: [gstreamer0.10-plugins-ugly]
#python-pyassimp:
#  ubuntu:
#    saucy: [python-pyassimp]
#libogre-dev:
#  ubuntu:
#    saucy: [libogre-1.8-dev]
gazebo:
  ubuntu: [gazebo5]
```
