### ISSUE TITLE
Problem with /mavros/setpoint_raw/attitude

### ISSUE THREAD

**Issue by yongjianwen** [mavlink/mavros#1225]
Hi, I am facing a problem with sending attitude command to the UAV via the `/mavros/setpoint_raw/attitude` topic. Previously, I have tried and succeeded in sending velocity command (in OFFBOARD mode) via the `/mavros/setpoint_velocity/cmd_vel` topic. In that case, I only sent the values in `Twist.Linear.X`, `Twist.Linear.Y`, `Twist.Linear.Z` and `Twist.Angular.Z`, and it worked perfectly with no errors. However, now that when I wanted to send attitude command in OFFBOARD mode, the QGroundControl would display an error message `Failsafe enabled: no offboard`.

![error](https://i.ibb.co/GnfMC11/Screenshot-from-2019-04-25-23-08-02.png)

I kept everything the same and the only difference is the topic used (`/mavros/setpoint_velocity/cmd_vel` versus `/mavros/setpoint_raw/attitude`). Also `rostopic echo /mavros/setpoint_raw/attitude` showed that the command has been received.

```
header:
  seq: 0
  stamp:
    secs: 0
    nsecs:        0
  frame_id: ''
type_mask: 0
orientation:
  x: 0.00569751797229
  y: -0.009772340308063
  z: 5.56814351204e-05
  w: 0.999936016594
body_rate:
  x: 0.0
  y: 0.0
  z: 0.0
thrust: 0.5789999996185
```

By the way, the simulation in Simulink and Gazebo worked fine with no issues. Only in real experiment then the OFFBOARD mode failed.

Could anyone help us figure out the problem causing the OFFBOARD mode to fail? Thanks in advance for helping!
