### ISSUE TITLE
boats in GUIDED mode  

### ISSUE THREAD

**Issue by BEZIA-EEA** [mavlink/mavros#1312]
### Issue details

Hello
I'm trying to control a simulated sailboat on Ardupilot STIL using marvos. my problem is that the véhicule won't be in GUIDED mode. I tried this code whit all vehicles. it worked but whit boats it does not woked.

### MAVROS version and platform

Mavros: 0.18.4
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[  ] ArduPilot

Version: ArduRover V3.6.0-dev"

****

### Node code 

```
#include <ros/ros.h>
#include <geometry_msgs/PoseStamped.h>
#include <mavros_msgs/CommandBool.h>
#include <mavros_msgs/SetMode.h>
#include <mavros_msgs/State.h>
#include <mavros_msgs/CommandTOL.h>

mavros_msgs::State current_state;
void state_cb(const mavros_msgs::State::ConstPtr& msg){
    current_state = *msg;
}

int main(int argc, char **argv)
{
    ros::init(argc, argv, "offb_node");
    ros::NodeHandle nh;

    ros::Subscriber state_sub = nh.subscribe<mavros_msgs::State>
            ("mavros/state", 10, state_cb);
    ros::Publisher local_pos_pub = nh.advertise<geometry_msgs::PoseStamped>
            ("mavros/setpoint_position/local", 10);
    ros::ServiceClient arming_client = nh.serviceClient<mavros_msgs::CommandBool>
            ("mavros/cmd/arming");
    ros::ServiceClient set_mode_client = nh.serviceClient<mavros_msgs::SetMode>
            ("mavros/set_mode");

    //the setpoint publishing rate MUST be faster than 2Hz
    ros::Rate rate(20.0);

    // wait for FCU connection
    ROS_INFO("wait for FCU connection");
    while(ros::ok() && !current_state.connected){
        ros::spinOnce();
        rate.sleep();
    }
    ROS_INFO("FCU connection established ");

    geometry_msgs::PoseStamped pose;
    pose.pose.position.x = 10;
    pose.pose.position.y = 0;
    pose.pose.position.z = 0;

    //send a few setpoints before starting
    ROS_INFO("sending few setpoints before starting");
    for(int i = 100; ros::ok() && i > 0; --i){
        local_pos_pub.publish(pose);
        ros::spinOnce();
        rate.sleep();
    }
    ROS_INFO("setpoints sended ");

    mavros_msgs::SetMode set_mode_guided;
    set_mode_guided.request.custom_mode = "GUIDED";

    mavros_msgs::CommandBool arm_cmd;
    arm_cmd.request.value = true;
    ros::Time last_request = ros::Time::now();


while(ros::ok())
	{
	if( current_state.mode != "GUIDED" && (ros::Time::now() - last_request > ros::Duration(5.0)))
	  {
	    ROS_INFO("changing mode to GUIDED mode ");
		if( set_mode_client.call(set_mode_guided) && set_mode_guided.response.mode_sent){
		        ROS_INFO("GUIDED mode enabled");
		  }
	    last_request = ros::Time::now();
	  } else 
	  {
		    if( !current_state.armed && (ros::Time::now() - last_request > ros::Duration(5.0))){
		        if( arming_client.call(arm_cmd) && arm_cmd.response.success){
		            ROS_INFO("Vehicle armed");
		        }
		        last_request = ros::Time::now();
		    }
	  }
        local_pos_pub.publish(pose);
        ros::spinOnce();
        rate.sleep();
        }

    return 0;
}

```

### Node logs

```
[ INFO] [1568125009.239649013]: wait for FCU connection
[ INFO] [1568125009.539807577]: FCU connection established 
[ INFO] [1568125009.539963433]: sending few setpoints before starting
[ INFO] [1568125014.539737935]: setpoints sended 
[ INFO] [1568125019.589749315]: changing mode to GUIDED mode 
[ INFO] [1568125024.639746236]: changing mode to GUIDED mode 
[ INFO] [1568125029.689801751]: changing mode to GUIDED mode 

```

### Diagnostics

```
header: 
  seq: 142
  stamp: 
    secs: 1568125053
    nsecs:  26955521
  frame_id: ''
status: 
  - 
    level: 0
    name: "mavros: FCU connection"
    message: "connected"
    hardware_id: "udp://127.0.0.1:14551@14555"
    values: 
      - 
        key: "Received packets:"
        value: "20315"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "9"
      - 
        key: "Tx sequence number:"
        value: "203"
      - 
        key: "Rx total bytes:"
        value: "654960"
      - 
        key: "Tx total bytes:"
        value: "113785"
      - 
        key: "Rx speed:"
        value: "5556.000000"
      - 
        key: "Tx speed:"
        value: "2450.000000"
  - 
    level: 0
    name: "mavros: GPS"
    message: "3D fix"
    hardware_id: "udp://127.0.0.1:14551@14555"
    values: 
      - 
        key: "Satellites visible"
        value: "10"
      - 
        key: "Fix type"
        value: "6"
      - 
        key: "EPH (m)"
        value: "1.21"
      - 
        key: "EPV (m)"
        value: "2.00"
  - 
    level: 0
    name: "mavros: Heartbeat"
    message: "Normal"
    hardware_id: "udp://127.0.0.1:14551@14555"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "173"
      - 
        key: "Frequency (Hz)"
        value: "1.040008"
      - 
        key: "Vehicle type"
        value: "Surface vessel"
      - 
        key: "Autopilot type"
        value: "ArduPilot"
      - 
        key: "Mode"
        value: "MANUAL"
      - 
        key: "System status"
        value: "Active"
  - 
    level: 0
    name: "mavros: System"
    message: "Normal"
    hardware_id: "udp://127.0.0.1:14551@14555"
    values: 
      - 
        key: "Sensor present"
        value: "0x0320DC2F"
      - 
        key: "Sensor enabled"
        value: "0x0020802F"
      - 
        key: "Sensor health"
        value: "0x0120812F"
      - 
        key: "3D gyro"
        value: "Ok"
      - 
        key: "3D accelerometer"
        value: "Ok"
      - 
        key: "3D magnetometer"
        value: "Ok"
      - 
        key: "absolute pressure"
        value: "Ok"
      - 
        key: "GPS"
        value: "Ok"
      - 
        key: "motor outputs / control"
        value: "Ok"
      - 
        key: "AHRS subsystem health"
        value: "Ok"
      - 
        key: "CPU Load (%)"
        value: "0.0"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 1
    name: "mavros: Battery"
    message: "Low voltage"
    hardware_id: "udp://127.0.0.1:14551@14555"
    values: 
      - 
        key: "Voltage"
        value: "0.00"
      - 
        key: "Current"
        value: "-0.0"
      - 
        key: "Remaining"
        value: "-1.0"
  - 
    level: 0
    name: "mavros: Time Sync"
    message: "Normal"
    hardware_id: "udp://127.0.0.1:14551@14555"
    values: 
      - 
        key: "Timesyncs since startup"
        value: "1770"
      - 
        key: "Frequency (Hz)"
        value: "10.000097"
      - 
        key: "Last RTT (ms)"
        value: "12.163061"
      - 
        key: "Mean RTT (ms)"
        value: "89.260962"
      - 
        key: "Last remote time (s)"
        value: "1063.905192000"
      - 
        key: "Estimated time offset (s)"
        value: "1568123989.148714304"

```
