### ISSUE TITLE
Difference between the accelerations : mavros/setpoint_accel/accel , mavros/setpoint_raw/local and, mavros/local_position/accel

### ISSUE THREAD

**Issue by Jaroan** [mavlink/mavros#1365]
I am trying to implement acceleration control on an Iris Quadrotor using PX4 SITL on ROS Gazebo 9 using Mavros. I want to use a local frame for getting the positions and velocities of the quadrotor and feed in the accelerations to the quad after using PD Control. I wanted to know the difference between these three topics that can be used to publish accelerations namely:
 
/mavros/local_position/accel [geometry_msgs/AccelWithCovarianceStamped] , mavros/setpoint_accel/accel [geometry_msgs/Vector3Stamped] ,
/mavros/setpoint_raw/local [mavros_msgs/PositionTarget] (geometry_msgs/Vector3 acceleration_or_force).

**Comment by Jaeyoung-Lim** [comment]
@Jaroan Acceler

**Comment by canberkgurel** [comment]
Setpoint topics are inputs to mavros and the other ones are the outputs. For instance, you can assign acceleration setpoint for the drone to converge, and then you can monitor the acceleration of the drone in real-time from the mavros/local_position/accel topic. I hope this helps.

**Comment by Jaroan** [comment]
Thank you very much for this info. Also, what is the difference betweensetpoint_raw and setpoint_accel?

**Comment by Jaeyoung-Lim** [comment]
@Jaroan It uses the same mavlink message. It just uses a different plugin in mavros

**Comment by Jaroan** [comment]
Oh alright, thank you for this info!

**Comment by Jaroan** [comment]
Update: I have used the following topics for position, velocity and acceleration controls:
```
#Subscribe to drone's local position
rospy.Subscriber('mavros/local_position/pose', PoseStamped, cnt.posCb)

#Subscribe to drone's velocity
rospy.Subscriber("/mavros/local_position/velocity", TwistStamped , cnt.velCb) 

#Setpoint publisher
sp_pub = rospy.Publisher('mavros/setpoint_raw/local', PositionTarget, queue_size=1)
```
 The command
`rostopic echo /mavros/setpoint_raw/local` shows that the required values are given to the quad as shown in the left terminal of the image:
![x_accel_y_accel_not_working](https://user-images.githubusercontent.com/34532876/70887592-57031800-2004-11ea-8db3-fc584dfd0084.jpeg)
```
---
header: 
  seq: 1620
  stamp: 
  secs: 0
    nsecs:         0
  frame_id: ''
coordinate_frame: 1
type_mask: 1080
position: 
  x: 0.0
  y: 0.0
  z: 4.0
velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
acceleration_or_force: 
  x: 1.60403175801
  y: 1.69204383269
  z: 0.0
yaw: 0.0
yaw_rate: 0.0
```
but the drone doesn't move from it's fixed altitude position. Just hovers around that point after giving a fixed set velocity and controlled accelerations.
