### ISSUE TITLE
FCU: arming denied check battery

### ISSUE THREAD

**Issue by pankhurivanjani** [mavlink/mavros#1377]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

_Please describe the problem, or desired feature_

### MAVROS version and platform

Mavros: ?0.18.4?
ROS: ?Melodic?
Ubuntu: ?18.04?

### Autopilot type and version

[  ] ArduPilot
[-- ] PX4

Version: ?3.7.1?

### Node logs

```

pankhuri@pankhuri-desktop:~$ roslaunch mavros px4.launch fcu_url:=/dev/ttyACM0
... logging to /home/pankhuri/.ros/log/f9e2e608-3b67-11ea-9d7e-00e04c680001/roslaunch-pankhuri-desktop-18243.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://pankhuri-desktop:42671/

SUMMARY
========

CLEAR PARAMETERS
* /mavros/

PARAMETERS
* /mavros/cmd/use_comp_id_system_control: False
* /mavros/conn/heartbeat_rate: 1.0
* /mavros/conn/system_time_rate: 1.0
* /mavros/conn/timeout: 10.0
* /mavros/conn/timesync_rate: 10.0
* /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
* /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
* /mavros/distance_sensor/hrlv_ez4_pub/id: 0
* /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270
* /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
* /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
* /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
* /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
* /mavros/distance_sensor/laser_1_sub/id: 3
* /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270
* /mavros/distance_sensor/laser_1_sub/subscriber: True
* /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
* /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
* /mavros/distance_sensor/lidarlite_pub/id: 1
* /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270
* /mavros/distance_sensor/lidarlite_pub/send_tf: True
* /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
* /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
* /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
* /mavros/distance_sensor/sonar_1_sub/id: 2
* /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270
* /mavros/distance_sensor/sonar_1_sub/subscriber: True
* /mavros/fake_gps/eph: 2.0
* /mavros/fake_gps/epv: 2.0
* /mavros/fake_gps/fix_type: 3
* /mavros/fake_gps/geo_origin/alt: 408.0

```
```
pankhuri@pankhuri-desktop:~$ rosrun mavros mavsafety arm
Request failed. Check mavros logs
```
### Diagnostics

```
pankhuri@pankhuri-desktop:~$ rostopic echo -n1 /diagnostics
header:
 seq: 139
 stamp:
   secs: 1579513015
   nsecs:  16779415
 frame_id: ''
status:
 -
   level: 0
   name: "mavros: FCU connection"
   message: "connected"
   hardware_id: "/dev/ttyACM0"
   values:
     -
       key: "Received packets:"
       value: "7802"
     -
       key: "Dropped packets:"
       value: "0"
     -
       key: "Buffer overruns:"
       value: "0"
     -
       key: "Parse errors:"
       value: "0"
     -
       key: "Rx sequence number:"
       value: "216"
     -
       key: "Tx sequence number:"
       value: "0"
     -
       key: "Rx total bytes:"
       value: "3931369"
     -
       key: "Tx total bytes:"
       value: "101541"
     -
       key: "Rx speed:"
       value: "22191.000000"
     -
       key: "Tx speed:"
       value: "570.000000"
 -
   level: 2
   name: "mavros: GPS"
   message: "No satellites"
   hardware_id: "/dev/ttyACM0"
   values:
     -
       key: "Satellites visible"
       value: "0"
     -
       key: "Fix type"
       value: "0"
     -
       key: "EPH (m)"
       value: "Unknown"
     -
       key: "EPV (m)"
       value: "Unknown"
 -
   level: 0
   name: "mavros: Heartbeat"
   message: "Normal"
   hardware_id: "/dev/ttyACM0"
   values:
     -
       key: "Heartbeats since startup"
       value: "177"
     -
       key: "Frequency (Hz)"
       value: "1.000007"
     -
       key: "Vehicle type"
       value: "Ground rover"
     -
       key: "Autopilot type"
       value: "PX4 Autopilot"
     -
       key: "Mode"
       value: "MANUAL"
     -
       key: "System status"
       value: "Standby"
 -
   level: 2
   name: "mavros: System"
   message: "Sensor health"
   hardware_id: "/dev/ttyACM0"
   values:
     -
       key: "Sensor present"
       value: "0x002E002F"
     -
       key: "Sensor enabled"
       value: "0x0021000F"
     -
       key: "Sensor health"
       value: "0x002E000F"
     -
       key: "3D gyro"
       value: "Ok"
     -
       key: "3D accelerometer"
       value: "Ok"
     -
       key: "3D magnetometer"
       value: "Ok"
     -
       key: "absolute pressure"
       value: "Ok"
     -
       key: "rc receiver"
       value: "Fail"
     -
       key: "AHRS subsystem health"
       value: "Ok"
     -
       key: "CPU Load (%)"
       value: "76.9"
     -
       key: "Drop rate (%)"
       value: "0.0"
     -
       key: "Errors comm"
       value: "0"
     -
       key: "Errors count #1"
       value: "0"
     -
       key: "Errors count #2"
       value: "0"
     -
       key: "Errors count #3"
       value: "0"
     -
       key: "Errors count #4"
       value: "0"
 -
   level: 0
   name: "mavros: Battery"
   message: "Normal"
   hardware_id: "/dev/ttyACM0"
   values:
     -
       key: "Voltage"
       value: "65.54"
     -
       key: "Current"
       value: "-0.0"
     -
       key: "Remaining"
       value: "-1.0"
 -
   level: 0


```

### Check ID

```
pankhuri@pankhuri-desktop:~$ rosrun mavros checkid
OK. I got messages from 1:1.

---
Received 6173 messages, from 1 addresses
sys:comp   list of messages
 1:1     0, 129, 2, 4, 1, 140, 141, 147, 26, 30, 31, 32, 36, 42, 74, 331, 77, 340, 230, 105, 111, 241, 116, 245

```
Hello!

I am trying to arm the pixhawk using Mavros. I am using pixhawk cube only with Jetson Nano, not any RC.  I Have calibrated the pixhawk using qgroundcontrol and probably gave a waypoint navigation too there.

Now, while I am trying to control the pixhawk with mavros, I am getting error **FCU: arming denied check battery**  in arming the vehicle. I intend to perform something similar to Hardware in the loop here. Can I do it without using RC, batteries and vehicle?
