### ISSUE TITLE
mavros load plan/waypoint error

### ISSUE THREAD

**Issue by 473867143** [mavlink/mavros#1403]
eason@eason:~/Desktop$ rosrun mavros mavwp load mission.plan 
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/mavros/mavwp", line 223, in <module>
    main()
  File "/opt/ros/melodic/lib/mavros/mavwp", line 219, in main
    args.func(args)
  File "/opt/ros/melodic/lib/mavros/mavwp", line 96, in do_load
    wps = [w for w in wps_file.read(args.file)]
  File "/opt/ros/melodic/lib/python2.7/dist-packages/mavros/mission.py", line 83, in read
    qgc, wpl, ver = data[0].split(' ', 3)
ValueError: need more than 1 value to unpack

----

### Issue details

i wang to use mavwp to load waypoints,I download .plan file from QGC,but when i run rosrun mavros mavwp load mission.plan 

### MAVROS version and platform

Mavros: ?1.14.3?
ROS: ?Melodic?
Ubuntu: ?18.04?

### Autopilot type and version

[  ] ArduPilot
[ * ] PX4

Version: ?V1.10.0?

### Node logs

```
eason@eason:~/Desktop$ rosrun mavros mavwp load mission.plan 
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/mavros/mavwp", line 223, in <module>
    main()
  File "/opt/ros/melodic/lib/mavros/mavwp", line 219, in main
    args.func(args)
  File "/opt/ros/melodic/lib/mavros/mavwp", line 96, in do_load
    wps = [w for w in wps_file.read(args.file)]
  File "/opt/ros/melodic/lib/python2.7/dist-packages/mavros/mission.py", line 83, in read
    qgc, wpl, ver = data[0].split(' ', 3)
ValueError: need more than 1 value to unpack

```

### Diagnostics

```
eason@eason:~/Desktop$ rostopic echo -n1 /diagnostics
header: 
  seq: 7041
  stamp: 
    secs: 1584959596
    nsecs: 119313185
  frame_id: ''
status: 
  - 
    level: 0
    name: "mavros: FCU connection"
    message: "connected"
    hardware_id: "udp://:14540@127.0.0.1:14557"
    values: 
      - 
        key: "Received packets:"
        value: "1271"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "26"
      - 
        key: "Tx sequence number:"
        value: "0"
      - 
        key: "Rx total bytes:"
        value: "223242854"
      - 
        key: "Tx total bytes:"
        value: "5332543"
      - 
        key: "Rx speed:"
        value: "35648.000000"
      - 
        key: "Tx speed:"
        value: "850.000000"
  - 
    level: 0
    name: "mavros: GPS"
    message: "3D fix"
    hardware_id: "udp://:14540@127.0.0.1:14557"
    values: 
      - 
        key: "Satellites visible"
        value: "10"
      - 
        key: "Fix type"
        value: "3"
      - 
        key: "EPH (m)"
        value: "0.00"
      - 
        key: "EPV (m)"
        value: "0.00"
  - 
    level: 0
    name: "mavros: Heartbeat"
    message: "Normal"
    hardware_id: "udp://:14540@127.0.0.1:14557"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "9207"
      - 
        key: "Frequency (Hz)"
        value: "1.037056"
      - 
        key: "Vehicle type"
        value: "Quadrotor"
      - 
        key: "Autopilot type"
        value: "PX4 Autopilot"
      - 
        key: "Mode"
        value: "AUTO.MISSION"
      - 
        key: "System status"
        value: "Standby"
  - 
    level: 0
    name: "mavros: System"
    message: "Normal"
    hardware_id: "udp://:14540@127.0.0.1:14557"
    values: 
      - 
        key: "Sensor present"
        value: "0x0020002F"
      - 
        key: "Sensor enabled"
        value: "0x0020000F"
      - 
        key: "Sensor health"
        value: "0x0020002F"
      - 
        key: "3D gyro"
        value: "Ok"
      - 
        key: "3D accelerometer"
        value: "Ok"
      - 
        key: "3D magnetometer"
        value: "Ok"
      - 
        key: "absolute pressure"
        value: "Ok"
      - 
        key: "AHRS subsystem health"
        value: "Ok"
      - 
        key: "CPU Load (%)"
        value: "0.0"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 0
    name: "mavros: Battery"
    message: "Normal"
    hardware_id: "udp://:14540@127.0.0.1:14557"
    values: 
      - 
        key: "Voltage"
        value: "12.15"
      - 
        key: "Current"
        value: "-1.0"
      - 
        key: "Remaining"
        value: "100.0"
  - 
    level: 0
    name: "mavros: Time Sync"
    message: "Normal"
    hardware_id: "udp://:14540@127.0.0.1:14557"
    values: 
      - 
        key: "Timesyncs since startup"
        value: "92075"
      - 
        key: "Frequency (Hz)"
        value: "10.000184"
      - 
        key: "Last RTT (ms)"
        value: "0.081618"
      - 
        key: "Mean RTT (ms)"
        value: "0.085109"
      - 
        key: "Last remote time (s)"
        value: "9209.276000000"
      - 
        key: "Estimated time offset (s)"
        value: "1584950386.835288525"
---
```

### Check ID

```
eason@eason:~/Desktop$ rosrun mavros checkid
OK. I got messages from 1:1.

---
Received 5985 messages, from 1 addresses
sys:comp   list of messages
  1:1     0, 1, 2, 4, 140, 141, 147, 24, 30, 31, 32, 33, 36, 74, 331, 76, 340, 230, 105, 111, 241, 242, 245
```
