### ISSUE TITLE
Message Mismatch between Mavros and ArduPlane

### ISSUE THREAD

**Issue by LightningPORTO** [mavlink/mavros#1441]
The /mavros/setpoint_position/global has the message type " geographic_msgs/GeoPoseStamped ", however, the ArduPlane firmware requests the same mavlink message ( SET_POSITION_TARGET_GLOBAL_INT (86) ) to have the structure as " mavros_msgs/GlobalPositionTarget " . 

So arduplane specifically requests " mavros_msgs/GlobalPositionTarget " but mavros only sends " geographic_msgs/GeoPoseStamped " on the same topic. 

Any work arrounds / suggestions?

**### MAVROS version and platform**

Mavros: Latest ( 17-july-2020 )
ROS: Melodic
Ubuntu: 18.04

**### Autopilot type and version**

[ X ] ArduPilot , ARDUPLANE 4.0
[  ] PX4

**### Diagnostics**

```
header: 
  seq: 51
  stamp: 
    secs: 1592402999
    nsecs: 447009274
  frame_id: ''
status: 
  - 
    level: 0
    name: "mavros: FCU connection"
    message: "connected"
    hardware_id: "udp://127.0.0.1:14551@14555"
    values: 
      - 
        key: "Received packets:"
        value: "9020"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "86"
      - 
        key: "Tx sequence number:"
        value: "0"
      - 
        key: "Rx total bytes:"
        value: "306626"
      - 
        key: "Tx total bytes:"
        value: "20400"
      - 
        key: "Rx speed:"
        value: "5963.000000"
      - 
        key: "Tx speed:"
        value: "500.000000"
  - 
    level: 0
    name: "mavros: GPS"
    message: "3D fix"
    hardware_id: "udp://127.0.0.1:14551@14555"
    values: 
      - 
        key: "Satellites visible"
        value: "10"
      - 
        key: "Fix type"
        value: "6"
      - 
        key: "EPH (m)"
        value: "1.21"
      - 
        key: "EPV (m)"
        value: "2.00"
  - 
    level: 0
    name: "mavros: Heartbeat"
    message: "Normal"
    hardware_id: "udp://127.0.0.1:14551@14555"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "62"
      - 
        key: "Frequency (Hz)"
        value: "0.962977"
      - 
        key: "Vehicle type"
        value: "Fixed wing aircraft"
      - 
        key: "Autopilot type"
        value: "ArduPilot"
      - 
        key: "Mode"
        value: "GUIDED"
      - 
        key: "System status"
        value: "Active"
  - 
    level: 0
    name: "mavros: System"
    message: "Normal"
    hardware_id: "udp://127.0.0.1:14551@14555"
    values: 
      - 
        key: "Sensor present"
        value: "0x1361FC3F"
      - 
        key: "Sensor enabled"
        value: "0x1161FC3F"
      - 
        key: "Sensor health"
        value: "0x1171FC3F"
      - 
        key: "3D gyro"
        value: "Ok"
      - 
        key: "3D accelerometer"
        value: "Ok"
      - 
        key: "3D magnetometer"
        value: "Ok"
      - 
        key: "absolute pressure"
        value: "Ok"
      - 
        key: "differential pressure"
        value: "Ok"
      - 
        key: "GPS"
        value: "Ok"
      - 
        key: "3D angular rate control"
        value: "Ok"
      - 
        key: "attitude stabilization"
        value: "Ok"
      - 
        key: "yaw position"
        value: "Ok"
      - 
        key: "z/altitude control"
        value: "Ok"
      - 
        key: "x/y position control"
        value: "Ok"
      - 
        key: "motor outputs / control"
        value: "Ok"
      - 
        key: "rc receiver"
        value: "Ok"
      - 
        key: "AHRS subsystem health"
        value: "Ok"
      - 
        key: "Terrain subsystem health"
        value: "Ok"
      - 
        key: "Logging"
        value: "Ok"
      - 
        key: "CPU Load (%)"
        value: "0.0"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 1
    name: "mavros: Battery"
    message: "Low voltage"
    hardware_id: "udp://127.0.0.1:14551@14555"
    values: 
      - 
        key: "Voltage"
        value: "0.00"
      - 
        key: "Current"
        value: "-0.0"
      - 
        key: "Remaining"
        value: "-1.0"
  - 
    level: 0
    name: "mavros: Time Sync"
    message: "Normal"
    hardware_id: "udp://127.0.0.1:14551@14555"
    values: 
      - 
        key: "Timesyncs since startup"
        value: "630"
      - 
        key: "Frequency (Hz)"
        value: "10.000221"
      - 
        key: "Last RTT (ms)"
        value: "25.375085"
      - 
        key: "Mean RTT (ms)"
        value: "17.026263"
      - 
        key: "Last remote time (s)"
        value: "1664.996358000"
      - 
        key: "Estimated time offset (s)"
        value: "1592401334.499280691"
---

```

**### Check ID**

```
OK. I got messages from 1:1.

---
Received 1808 messages, from 1 addresses
sys:comp   list of messages
  1:1     0, 1, 2, 129, 136, 11020, 152, 150, 24, 27, 29, 30, 32, 33, 163, 36, 165, 168, 42, 178, 62, 65, 74, 193, 87, 164, 111, 241, 242, 116, 125

```
