### ISSUE TITLE
Angular Velocity units.

### ISSUE THREAD

**Issue by tonybaltovski** [mavlink/mavros#152]
I am getting rather large numbers from the imu/data_raw.

```
header: 
  seq: 822
  stamp: 
    secs: 1410290457
    nsecs: 796240137
  frame_id: fcu
orientation: 
  x: 0.0
  y: 0.0
  z: 0.0
  w: 0.0
orientation_covariance: [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: 325000.0
  y: 524000.0
  z: 235000.0
angular_velocity_covariance: [1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07]
linear_acceleration: 
  x: 0.588399
  y: -0.8041453
  z: 10.2381426
linear_acceleration_covariance: [8.999999999999999e-08, 0.0, 0.0, 0.0, 8.999999999999999e-08, 0.0, 0.0, 0.0, 8.999999999999999e-08]
```
