### ISSUE TITLE
Multiple issues navigating to waypoints using mavros_msgs::globalpositiontarget

### ISSUE THREAD

**Issue by abhiramdapke** [mavlink/mavros#1553]
Mavros: 1.5
ROS: Melodic
Ubuntu: 18.04

[ Y ] ArduPilot

Hi guys, 
I am trying to implement a GPS function by passing multiple waypoints to the drone using mavros and would like to implement it with a real drone with a companion computer. Currently, I am trying to accomplish it in the simulation space(Gazebo). I am using mavros_msgs::globalpositiontarget msg to pass the waypoints and sensor_msgs::NatSatFix to get the location of the drone.

The subscriber callback for getting the global position is -
```
void globalPosition_cb(const sensor_msgs::NavSatFix::ConstPtr& msg) {
    global_position = *msg;
    gps_position_received = true;
    ROS_INFO("Received global position: [%f, %f, %f]", global_position.latitude, global_position.longitude, global_position.altitude);
}
```
For this, the subscriber is - 
```
ros::Subscriber global_pos_sub = waypoint_node.subscribe<sensor_msgs::NavSatFix>("mavros/global_position/global", 10, globalPosition_cb);
```
The function for the waypoint is -
```
void set_waypoint(float lat, float lon, float alt)
{
	mavros_msgs::GlobalPositionTarget goal_position;
	goal_position.coordinate_frame = goal_position.FRAME_GLOBAL_TERRAIN_ALT;
	goal_position.type_mask = goal_position.IGNORE_VX | goal_position.IGNORE_VY | goal_position.IGNORE_VZ | goal_position.IGNORE_AFX | goal_position.IGNORE_AFY | goal_position.IGNORE_AFZ | goal_position.IGNORE_YAW | goal_position.IGNORE_YAW_RATE;
        goal_position.latitude = lat;
        goal_position.longitude = lon;
        goal_position.altitude = alt;
	global_pos_pub_gps.publish(goal_position);
}
```
For this, the Publisher is - 
```
ros::Publisher global_pos_pub_gps = waypoint_node.advertise<mavros_msgs::GlobalPositionTarget>("/mavros/setpoint_raw/global",10);
```

A snippet of the script that I am using is like this -
```
struct waypoint
{
	float lat; 
	float lon; 
	float alt; 
};
```
 ---------------------------
```
    ros::Rate rate(2.0);
    wait4connect();
    wait4start();
    

    takeoff(5);
    sleep(4);
    
    std::vector<waypoint> waypointlist;
    waypoint nextwp;
    nextwp.lat = 0;
    nextwp.lon = 0;
    nextwp.alt = 5;
    waypointlist.push_back(nextwp);

    nextwp.lat = -35.3613525;
    nextwp.lon = 149.1579742;
    nextwp.alt = 5;
    waypointlist.push_back(nextwp);

    nextwp.lat = -35.3613530;
    nextwp.lon = 149.1579735;
    nextwp.alt = 5;
    waypointlist.push_back(nextwp);

    nextwp.lat = -35.3613535;
    nextwp.lon = 149.1579730;
    nextwp.alt = 5;
    waypointlist.push_back(nextwp);
    
    int i = 0;
    //wait for position information
    while(ros::ok() && !gps_position_received) 
    {
	ROS_INFO_ONCE("Waiting for GPS signal");
        ros::spinOnce();
        rate.sleep();
        
        ROS_INFO_ONCE("GPS position received");

	if(i < waypointlist.size())
	{
		set_waypoint(waypointlist[i].lat,waypointlist[i].lon,waypointlist[i].alt);
		ROS_INFO("GPS position sent: [%f %f %f]", waypointlist[i].lat, waypointlist[i].lon, waypointlist[i].alt);
		i++;
		sleep(4);
		/*while (waypoint_reached(waypointlist[i].lat, waypointlist[i].lon)!= 1)	
		{		
		if (waypoint_reached(waypointlist[i].lat, waypointlist[i].lon)== 1)
		{
			i++;
			break;
		}
		else
		{
			continue;		
		}}*/
		//sleep(5);	
	}
	else
	{
		land();
	} 
       
    }
    return 0;
}
```

For checking if the waypoint is reached, I am using Haversine's formula to get the distance between two GPS waypoints like this. It is taking the target location and subtracting that from the current location(which is derived from the global_Position_cb) - 
```
bool waypoint_reached(float tlat, float tlon)
{
    double pi = 3.14159265359;
    double degToRad = pi/180.0;

    //Haversine Formula - Calculate great-circle distance betweeen two points
    float currentLat = global_position.latitude;
    float currentLong = global_position.longitude;

    double eLat = degToRad*(tlat - currentLat);
    double eLong = degToRad*(tlon - currentLong);

    double a = sin(eLat/2)*sin(eLat/2) + cos(degToRad*currentLat)*cos(degToRad*tlat)*sin(eLong/2)*sin(eLong/2);
    double c = 2*atan2(sqrt(a),sqrt(1-a));
    float dist = (float) (6371000 * c);

    double tolerance = 0.3;

    if (abs(dist) < tolerance)
    {
      ROS_INFO_ONCE("Provided waypoint reached");
      return true;
    }
    else
    {
       return false;
    }

}
```

There are a multitude of issues I am facing - 
1. when I run the above script, the drone takes-off at the provided altitude but before reaching that altitude, it starts navigating towards the waypoint provided by set_waypoint. so, it doesn't actually reach the given altitude i.e. the function doesn't get completed thoroughly but the program moves on to the next line. I am using a temporary sleep() so that it reaches the provided altitude but need a more concrete solution.

2. The same is happening with the set_waypoint function. On the terminal, I get ROS_INFO("GPS position sent: [%f %f %f]", waypointlist[i].lat, waypointlist[i].lon, waypointlist[i].alt) msg for all the 4 waypoints almost immediately so what happens is that the drone doesn't reach the provided waypoint and turns around towards the next one. Set_waypoint is not getting completed and the program is moving to the next line. I surmised this might be because of the while(rosok()) loop and the rate set for receiving msgs but couldn't figure out a workaround. That is why I wrote a waypoint_reached function to check if the waypoint is actually reached before the program moves ahead. Not sure if anything is wrong with the logic of the set_waypoint or the waypoint_reached function or implementation of both of them. When running this program with the waypoint_reached function uncommented, I only get GPS position sent: once and nothing happens after that as the drone is flying off to the waypoint.

3. Echoing the topic /mavros/global_position/global fluctuates the lat lon values and those values are not necessarily within the waypoints specified. I suppose the home position in gazebo is lat = -35.362 and lon = 149.161 because that's what I get when I echo this topic. Not sure how the gazebo sets its home position and whether it is possible to visualize the drone actually moving to multiple waypoints in the gazebo in WGS84. The reason I say this is because no matter what waypoint is provided to the set_waypoint, it goes in the direction of the waypoint indefinitely. I am not sure if the drone will stop after reaching that waypoint or just crash.

4. Echoing the topic /mavros/global_position/global shows an altitude of 608m but the drone rises to only 5m with the takeoff client. I found an issue on Github that mentions that the altitude is either in ASML or WGS84 which might cause an issue but didn't find a solution to fix it so that I can visualize the correct altitude in the gazebo during the simulation.

5. In the rqt graph, I am not sure is everything is connected where it needs to be. If you could confirm that, that would be great. Also, what is /rostopic_10114_161547 and /rostopic_10144_161547?

Log of rostopic echo /mavros/global_position/global
```
status: 
  status: 0
  service: 1
latitude: -35.3624209
longitude: 149.161684
altitude: 608.365077318
position_covariance: [0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001]
position_covariance_type: 2
---
header: 
  seq: 307
  stamp: 
    secs: 163
    nsecs: 253040248
  frame_id: "base_link"
status: 
  status: 0
  service: 1
latitude: -35.362418
longitude: 149.1616713
altitude: 608.365064351
position_covariance: [0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001]
position_covariance_type: 2
---
header: 
  seq: 308
  stamp: 
    secs: 163
    nsecs: 493059935
  frame_id: "base_link"
status: 
  status: 0
  service: 1
latitude: -35.362415
longitude: 149.1616586
altitude: 608.365051502
position_covariance: [0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001]
position_covariance_type: 2
---
header: 
  seq: 309
  stamp: 
    secs: 163
    nsecs: 733092246
  frame_id: "base_link"
status: 
  status: 0
  service: 1
latitude: -35.3624121
longitude: 149.1616459
altitude: 608.355038533
position_covariance: [0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001]
position_covariance_type: 2
---
header: 
  seq: 310
  stamp: 
    secs: 163
    nsecs: 973113142
  frame_id: "base_link"
status: 
  status: 0
  service: 1
latitude: -35.3624091
longitude: 149.1616331
altitude: 608.355025552
position_covariance: [0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001]
position_covariance_type: 2
---
header: 
  seq: 311
  stamp: 
    secs: 164
    nsecs: 213140527
  frame_id: "base_link"
status: 
  status: 0
  service: 1
latitude: -35.3624062
longitude: 149.1616204
altitude: 608.355012582
position_covariance: [0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001]
position_covariance_type: 2
---
header: 
  seq: 312
  stamp: 
    secs: 164
    nsecs: 453161142
  frame_id: "base_link"
status: 
  status: 0
  service: 1
latitude: -35.3624032
longitude: 149.1616077
altitude: 608.354999729
position_covariance: [0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001, 0.0, 0.0, 0.0, 0.04000000000000001]
position_covariance_type: 2
---
```
Log of rostopic echo /mavros/setpoint_raw/global
```
coordinate_frame: 11
type_mask: 3576
latitude: 0.0
longitude: 0.0
altitude: 5.0
velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
acceleration_or_force: 
  x: 0.0
  y: 0.0
  z: 0.0
yaw: 0.0
yaw_rate: 0.0
---
header: 
  seq: 34
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
coordinate_frame: 11
type_mask: 3576
latitude: 0.0
longitude: 0.0
altitude: 5.0
velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
acceleration_or_force: 
  x: 0.0
  y: 0.0
  z: 0.0
yaw: 0.0
yaw_rate: 0.0
---
header: 
  seq: 35
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
coordinate_frame: 11
type_mask: 3576
latitude: 0.0
longitude: 0.0
altitude: 5.0
velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
acceleration_or_force: 
  x: 0.0
  y: 0.0
  z: 0.0
yaw: 0.0
yaw_rate: 0.0
---
header: 
  seq: 36
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
coordinate_frame: 11
type_mask: 3576
latitude: 0.0
longitude: 0.0
altitude: 5.0
velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
acceleration_or_force: 
  x: 0.0
  y: 0.0
  z: 0.0
yaw: 0.0
yaw_rate: 0.0
---
header: 
  seq: 37
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
coordinate_frame: 11
type_mask: 3576
latitude: 0.0
longitude: 0.0
altitude: 5.0
velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
acceleration_or_force: 
  x: 0.0
  y: 0.0
  z: 0.0
yaw: 0.0
yaw_rate: 0.0
---
header: 
  seq: 38
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
coordinate_frame: 11
type_mask: 3576
latitude: 0.0
longitude: 0.0
altitude: 5.0
velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
acceleration_or_force: 
  x: 0.0
  y: 0.0
  z: 0.0
yaw: 0.0
yaw_rate: 0.0
---
header: 
  seq: 39
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
coordinate_frame: 11
type_mask: 3576
latitude: 0.0
longitude: 0.0
altitude: 5.0
velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
acceleration_or_force: 
  x: 0.0
  y: 0.0
  z: 0.0
yaw: 0.0
yaw_rate: 0.0
---

```
Image of rqt graph

![rosgraph](https://user-images.githubusercontent.com/47953521/110822228-7b28c580-8256-11eb-9011-e5dc5de462b7.png)

I am working on these for the past few weeks and not yet able to accomplish a working GPS function so any insights or guidance would be highly appreciated. Please feel free to share a snippet of your code as that becomes easier to understand.
Thanks in advance!

**Comment by burak-yildizoz** [comment]
Try using `mavros_msgs::Altitude::amsl` as home altitude.

``` c++
double latitude, longitude;
bool gps_received = false;
void get_global_pose (const sensor_msgs::NavSatFix::ConstPtr& msg) {
	latitude = msg->latitude;
	longitude = msg->longitude;
	gps_received = true;
}

double altitude;
void get_altitude(const mavros_msgs::Altitude::ConstPtr &msg)
{
    altitude = msg->amsl;
}
```

Set `home_alt` to `altitude` when `gps_received` becomes true, and publish to `setpoint_position/global` using `geographic_msgs::GeoPoseStamped`.

**Comment by murphym18** [comment]
I've also been trying to control the drone with the same type of message, but with python. I've noticed issues too. But much of what I do is quite different.

1. I takeoff by putting the drone in takeoff mode (`AUTO.TAKEOFF`). 
1. I look at the `mavros/extended_state` and `mavros/global_position/rel_alt` messages. I don't move on until `landed_state == 2` and I've reached a high enough relative altitude (in my case I need to be at least 2 meters up).
2. I send 20 setpoint messages at a rate of 10 per second. Then I switch to offboard mode. I continue to send set point messages at the same rate after that.
3. I look at  `mavros/global_position/global` messages. I check to see how many meters away my target position is from my current position. And this is where I get stuck.

The drone flies to the right latitude and longitude, but it's altitude is wrong. Here are the details from my log message:
```
distance: 47.21 meters 

                  LATITUDE           LONGITUDE          ALTITUDE
current position: 47.3978429,        8.545869,          597.5515792976987
target position:  47.39784293752265, 8.545869057172045, 550.3417375283871
```

The altitude accounts for all the distance.

@burak-yildizoz I've also tried sending `GeoPoseStamped` messages and I get the same problem where the drone flies 47.2 meters too high.

By the way, I calculate the distance by converting both my current position and target position to X, Y, Z values in WGS84 coordinates (each component is in meters), sometimes this is called ECEF. Then I use the Pythagorean theorem to find the distance. Getting the X, Y, and Z values is tricky and I can share some python with you, if you'd like. But I use the tricks from [the n-vector page](https://www.navlab.net/nvector/) for the heavy lifting.

**Comment by murphym18** [comment]
@burak-yildizoz I'm not sure what you mean by:

>Try using mavros_msgs::Altitude::amsl as home altitude.

and

>Set home_alt to altitude when gps_received becomes true

Does the drone's home altitude have something to do with how `GeoPoseStamped` messages are interpreted? When I run `rostopic echo mavros/home_position/home` Here's what I see
```
geo: 
  latitude: 47.3978435
  longitude: 8.5458706
  altitude: 535.3505773470537
position: 
  x: 19.823331832885742
  y: 10.315902709960938
  z: 0.02930159494280815
```

Should I change `position.z` to `535`?
