### ISSUE TITLE
gcs_url working with UDP not with TCP

### ISSUE THREAD

**Issue by Karthikai-28** [mavlink/mavros#1589]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

_Please describe the problem, or desired feature_

In apm.launch file, if I use UDP for gcs_url, it works well, when I try to use TCP it throws and mavros is not starting sometimes, even though the Mavros starts it's not publishing all the topics need to be published.

### MAVROS version and platform

Mavros: ?1.2.0-beta4?
ROS: ?Noetic?
Ubuntu: ?Raspbian - RPi?

### Autopilot type and version

[  ] ArduPilot

Version: ?3.7.1?

### Node logs

```
copy output of mavros_node. Usually console where you run roslaunch
```
[ INFO] [1625219067.613155810]: FCU URL: /dev/ttyACM0:921600
[ INFO] [1625219067.621159520]: serial0: device: /dev/ttyACM0 @ 921600 bps
[ INFO] [1625219067.623776832]: GCS URL: udp://@192.168.1.112:6010
[ INFO] [1625219067.624774305]: udp1: Bind address: 0.0.0.0:14555
[ INFO] [1625219067.625385596]: udp1: Remote address: 192.168.1.112:6010
[ INFO] [1625219067.685337889]: Plugin 3dr_radio loaded
[ INFO] [1625219067.696216909]: Plugin 3dr_radio initialized
[ INFO] [1625219067.696436667]: Plugin actuator_control blacklisted
[ INFO] [1625219067.727022373]: Plugin adsb loaded
[ INFO] [1625219067.739065439]: Plugin adsb initialized
[ INFO] [1625219067.739275567]: Plugin altitude blacklisted
[ INFO] [1625219067.739663249]: Plugin cam_imu_sync loaded
[ INFO] [1625219067.742252449]: Plugin cam_imu_sync initialized
[ INFO] [1625219067.742763556]: Plugin command loaded
[ INFO] [1625219067.768169602]: Plugin command initialized
[ INFO] [1625219067.768584321]: Plugin companion_process_status loaded
[ INFO] [1625219067.778002853]: Plugin companion_process_status initialized
[ INFO] [1625219067.778121222]: Plugin debug_value blacklisted
[ INFO] [1625219067.778521052]: Plugin distance_sensor loaded
[ INFO] [1625219067.809214554]: Plugin distance_sensor initialized
[ INFO] [1625219067.810024936]: Plugin esc_status loaded
[ INFO] [1625219067.815137282]: Plugin esc_status initialized
[ INFO] [1625219067.815915387]: Plugin fake_gps loaded
[ INFO] [1625219067.883922298]: Plugin fake_gps initialized
[ INFO] [1625219067.884489052]: Plugin ftp blacklisted
[ INFO] [1625219067.885247953]: Plugin global_position loaded
[ INFO] [1625219067.963860627]: Plugin global_position initialized
[ INFO] [1625219067.964273180]: Plugin gps_rtk loaded
[ INFO] [1625219067.977192849]: Plugin gps_rtk initialized
[ INFO] [1625219067.977539809]: Plugin gps_status loaded
[ INFO] [1625219067.986620622]: Plugin gps_status initialized
[ INFO] [1625219067.986742121]: Plugin hil blacklisted
[ INFO] [1625219067.987129729]: Plugin home_position loaded
[ INFO] [1625219068.001583959]: Plugin home_position initialized
[ INFO] [1625219068.002005067]: Plugin imu loaded
[ INFO] [1625219068.017864323]: udp1: Remote address: 192.168.1.112:6010
[ INFO] [1625219068.032048389]: Plugin imu initialized
[ INFO] [1625219068.032412942]: Plugin landing_target loaded
[ INFO] [1625219068.089526982]: Plugin landing_target initialized
[ INFO] [1625219068.089945016]: Plugin local_position loaded
[ INFO] [1625219068.116595237]: Plugin local_position initialized
[ INFO] [1625219068.116980567]: Plugin log_transfer loaded
[ INFO] [1625219068.127042353]: Plugin log_transfer initialized
[ INFO] [1625219068.127476016]: Plugin manual_control loaded
[ INFO] [1625219068.139375750]: Plugin manual_control initialized
[ INFO] [1625219068.139959227]: Plugin mocap_pose_estimate loaded
[ INFO] [1625219068.163381956]: Plugin mocap_pose_estimate initialized
[ INFO] [1625219068.163816675]: Plugin mount_control loaded
[ INFO] [1625219068.186441930]: Plugin mount_control initialized
[ INFO] [1625219068.186906185]: Plugin obstacle_distance loaded
[ INFO] [1625219068.202153539]: Plugin obstacle_distance initialized
[ INFO] [1625219068.202571702]: Plugin odom loaded
[ INFO] [1625219068.223930579]: Plugin odom initialized
[ INFO] [1625219068.224339428]: Plugin onboard_computer_status loaded
[ INFO] [1625219068.238988972]: Plugin onboard_computer_status initialized
[ INFO] [1625219068.239553467]: Plugin param loaded
[ INFO] [1625219068.253594497]: Plugin param initialized
[ INFO] [1625219068.253794014]: Plugin px4flow blacklisted
[ INFO] [1625219068.254137622]: Plugin rangefinder loaded
[ INFO] [1625219068.256883266]: Plugin rangefinder initialized
[ INFO] [1625219068.257324688]: Plugin rc_io loaded
[ INFO] [1625219068.274454730]: Plugin rc_io initialized
[ INFO] [1625219068.274628803]: Plugin safety_area blacklisted
[ INFO] [1625219068.274965226]: Plugin setpoint_accel loaded
[ INFO] [1625219068.289752232]: Plugin setpoint_accel initialized
[ INFO] [1625219068.290378319]: Plugin setpoint_attitude loaded
[ INFO] [1625219068.328173503]: Plugin setpoint_attitude initialized
[ INFO] [1625219068.328892126]: Plugin setpoint_position loaded
[ INFO] [1625219068.378888541]: Plugin setpoint_position initialized
[ INFO] [1625219068.379287556]: Plugin setpoint_raw loaded
[ INFO] [1625219068.406362163]: Plugin setpoint_raw initialized
[ INFO] [1625219068.406743882]: Plugin setpoint_trajectory loaded
[ INFO] [1625219068.422609305]: Plugin setpoint_trajectory initialized
[ INFO] [1625219068.423008801]: Plugin setpoint_velocity loaded
[ INFO] [1625219068.443348353]: Plugin setpoint_velocity initialized
[ INFO] [1625219068.443866090]: Plugin sys_status loaded
[ INFO] [1625219068.487476928]: Plugin sys_status initialized
[ INFO] [1625219068.488293458]: Plugin sys_time loaded
[ INFO] [1625219068.506172216]: TM: Timesync mode: MAVLINK
[ INFO] [1625219068.510313052]: Plugin sys_time initialized
[ INFO] [1625219068.511554486]: Plugin trajectory loaded
[ INFO] [1625219068.533111583]: Plugin trajectory initialized
[ INFO] [1625219068.533844984]: Plugin vfr_hud loaded
[ INFO] [1625219068.538572852]: Plugin vfr_hud initialized
[ INFO] [1625219068.538771499]: Plugin vibration blacklisted
[ INFO] [1625219068.539156107]: Plugin vision_pose_estimate loaded
[ INFO] [1625219068.572624549]: Plugin vision_pose_estimate initialized
[ INFO] [1625219068.572764566]: Plugin vision_speed_estimate blacklisted
[ INFO] [1625219068.573110637]: Plugin waypoint loaded
[ INFO] [1625219068.589589184]: Plugin waypoint initialized
[ INFO] [1625219068.589719609]: Plugin wheel_odometry blacklisted
[ INFO] [1625219068.590065680]: Plugin wind_estimation loaded
[ INFO] [1625219068.592370532]: Plugin wind_estimation initialized
[ INFO] [1625219068.592551160]: Built-in SIMD instructions: None
[ INFO] [1625219068.592627400]: Built-in MAVLink package version: 2020.8.8
[ INFO] [1625219068.593621780]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1625219068.594060443]: RC_CHANNELS message detected!
[ INFO] [1625219068.594344422]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ INFO] [1625219068.594825548]: IMU: Raw IMU message used.
[ WARN] [1625219068.595007306]: IMU: linear acceleration on RAW_IMU known on APM only.
[ WARN] [1625219068.595124953]: IMU: ~imu/data_raw stores unscaled raw acceleration report.
[ WARN] [1625219068.595809910]: GP: No GPS fix
[ WARN] [1625219068.596237758]: TM: Wrong FCU time.
[ INFO] [1625219068.872561519]: CON: Got HEARTBEAT, connected. FCU: ArduPilot
[ INFO] [1625219068.893599176]: RC_CHANNELS message detected!
[ WARN] [1625219069.882795778]: CMD: Unexpected command 520, result 0
[ INFO] [1625219069.883978379]: WP: Using MISSION_ITEM_INT
[ INFO] [1625219069.884431524]: VER: 1.1: Capabilities         0x000000000000fbef
[ INFO] [1625219069.884819354]: VER: 1.1: Flight software:     040007ff ( 0bb18a1)
[ INFO] [1625219069.885210758]: VER: 1.1: Middleware software: 00000000 (        )
[ INFO] [1625219069.885589921]: VER: 1.1: OS software:         00000000 ( d4fce84)
[ INFO] [1625219069.885959622]: VER: 1.1: Board hardware:      00000000
[ INFO] [1625219069.886325582]: VER: 1.1: VID/PID:             0000:0000
[ INFO] [1625219069.886694820]: VER: 1.1: UID:                 0000000000000000
### Diagnostics

```
place here result of:
rostopic echo -n1 /diagnostics
header: 
  seq: 2875
  stamp: 
    secs: 1625218855
    nsecs: 314621600
  frame_id: ''
status: 
  - 
    level: 0
    name: "mavros: FCU connection"
    message: "connected"
    hardware_id: "/dev/ttyACM0:921600"
    values: 
      - 
        key: "Received packets:"
        value: "41469"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "71"
      - 
        key: "Tx sequence number:"
        value: "0"
      - 
        key: "Rx total bytes:"
        value: "14977950"
      - 
        key: "Tx total bytes:"
        value: "696570"
      - 
        key: "Rx speed:"
        value: "11334.000000"
      - 
        key: "Tx speed:"
        value: "502.000000"
  - 
    level: 2
    name: "mavros: GPS"
    message: "No satellites"
    hardware_id: "/dev/ttyACM0:921600"
    values: 
      - 
        key: "Satellites visible"
        value: "0"
      - 
        key: "Fix type"
        value: "1"
      - 
        key: "EPH (m)"
        value: "100.00"
      - 
        key: "EPV (m)"
        value: "100.00"
  - 
    level: 0
    name: "mavros: Heartbeat"
    message: "Normal"
    hardware_id: "/dev/ttyACM0:921600"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "1994"
      - 
        key: "Frequency (Hz)"
        value: "1.034492"
      - 
        key: "Vehicle type"
        value: "Quadrotor"
      - 
        key: "Autopilot type"
        value: "ArduPilot"
      - 
        key: "Mode"
        value: "STABILIZE"
      - 
        key: "System status"
        value: "Standby"
  - 
    level: 2
    name: "mavros: System"
    message: "Sensor health"
    hardware_id: "/dev/ttyACM0:921600"
    values: 
      - 
        key: "Sensor present"
        value: "0x1360FC2F"
      - 
        key: "Sensor enabled"
        value: "0x12609C2F"
      - 
        key: "Sensor health"
        value: "0x03709C2F"
      - 
        key: "3D gyro"
        value: "Ok"
      - 
        key: "3D accelerometer"
        value: "Ok"
      - 
        key: "3D magnetometer"
        value: "Ok"
      - 
        key: "absolute pressure"
        value: "Ok"
      - 
        key: "GPS"
        value: "Ok"
      - 
        key: "3D angular rate control"
        value: "Ok"
      - 
        key: "attitude stabilization"
        value: "Ok"
      - 
        key: "yaw position"
        value: "Ok"
      - 
        key: "motor outputs / control"
        value: "Ok"
      - 
        key: "AHRS subsystem health"
        value: "Ok"
      - 
        key: "Terrain subsystem health"
        value: "Ok"
      - 
        key: "Battery"
        value: "Ok"
      - 
        key: "CPU Load (%)"
        value: "14.5"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 1
    name: "mavros: Battery"
    message: "Low voltage"
    hardware_id: "/dev/ttyACM0:921600"
    values: 
      - 
        key: "Voltage"
        value: "0.04"
      - 
        key: "Current"
        value: "-0.0"
      - 
        key: "Remaining"
        value: "-1.0"
  - 
    level: 0
    name: "mavros: Time Sync"
    message: "Normal"
    hardware_id: "/dev/ttyACM0:921600"
    values: 
      - 
        key: "Timesyncs since startup"
        value: "19348"
      - 
        key: "Frequency (Hz)"
        value: "10.000173"
      - 
        key: "Last RTT (ms)"
        value: "3.979577"
      - 
        key: "Mean RTT (ms)"
        value: "5.051204"
      - 
        key: "Last remote time (s)"
        value: "2036.858542000"
      - 
        key: "Estimated time offset (s)"
        value: "1625216818.356428623"
```

### Check ID

```
rosrun mavros checkid

OK. I got messages from 1:1.

---
Received 3668 messages, from 2 addresses
sys:comp   list of messages
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/srv/maverick/software/python/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/ros/noetic/lib/python3.7/site-packages/rospy/timer.py", line 234, in run
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
  File "/opt/ros/noetic/lib/mavros/checkid", line 82, in timer_cb
    for address, messages in self.message_sources.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```
