### ISSUE TITLE
LandingTarget position_valid in python

### ISSUE THREAD

**Issue by Y-H-Park** [mavlink/mavros#1643]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details
We are simulated LandingTarget using mavros, python in Gazebo. Other variables of LandingTarget are used, but, there is no part about the "position_valid".
Inputs the position and pose of LandingTarget.pose are good, but it is not working. I wonder if position_valid in python is not suppoted in LandingTarget.
I research Auto Drone Station. so, it is very very important for me. 
Any other solution ??
Thank you!

### MAVROS version and platform

Mavros: ?0.18.4?
ROS: Melodic
Ubuntu: 18.04

### Autopilot type and version

[O] ArduPilot
[  ] PX4

Version: ?3.7.1?

### Node logs

```

### Diagnostics

```
```
header: 
  seq: 24962
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: "map"
target_num: 0
frame: 9
angle: [0.47360944747924805, -0.17104771733283997]
distance: 5.01578426361
size: [1.0, 1.0]
pose: 
  position: 
    x: 2.57066499141
    y: -0.866404584033
    z: 5.01578449959
  orientation: 
    x: 0.0524738328068
    y: -0.00854498640532
    z: 0.985223288658
    w: 0.162814469762
type: 2
"position_valid" : where (?) 
---
```
