### ISSUE TITLE
Rosettadrone 2 <-UDP-> MAVROS works only unidirectional

### ISSUE THREAD

**Issue by MariusBeul** [mavlink/mavros#1687]
### Issue details

My connection looks like this: [Rosettadrone 2](https://github.com/The1only/rosettadrone) <-UDP-> MAVROS
I can receive data from the drone but cannot publish anything with MAVROS. No heartbeat arrives at the drone.
If I use Qgroundcontrol instead of MAVROS ([Rosettadrone 2](https://github.com/The1only/rosettadrone) <-UDP-> QGroundcontrol), the bidirectional UDP connection works and also the heartbeat comes through.
The telemetry port in [Rosettadrone 2](https://github.com/The1only/rosettadrone) is set to 14550.
I tried many different fcu_urls and receiving data works for example with

fcu_url:=udp://:14550@:14555/?ids=255,1" 
fcu_url:=udp://:14550@
fcu_url:=udp://:14550@:33749

The gcs_url is empty. Many messages arrive on the "/mavlink/from" topic, but on "/mavlink/to" nothing is published. Shouldn't I see the heartbeat from MAVROS here?

**Am I doing something wrong connectionwise?**
Thank you for your support!

### MAVROS version and platform

Mavros: The version that comes with ros-melodic-mavros and the current master branch.
ROS: Melodic
Ubuntu: 18.04

### Autopilot type and version

[X] ArduPilot
[  ] PX4

Version: ?3.7.1?

### Node logs

```
[ INFO] [1641480350.446197624]: MAVROS started. MY ID 255.1, TARGET ID 1.1
[ INFO] [1641480356.529426617]: udp0: Remote address: 192.168.0.10:33749
[ WARN] [1641480356.634363808]: RADIO_STATUS not from 3DR modem?
[ INFO] [1641480356.636827616]: RC_CHANNELS message detected!
[ INFO] [1641480356.984039894]: CON: Got HEARTBEAT, connected. FCU: ArduPilot
[ INFO] [1641480357.087527805]: RC_CHANNELS message detected!
[ WARN] [1641480359.000536118]: VER: broadcast request timeout, retries left 4
[ WARN] [1641480360.004007925]: VER: broadcast request timeout, retries left 3
[ WARN] [1641480366.000325425]: CMD: Command 520 -- wait ack timeout
[ WARN] [1641480366.003431409]: VER: unicast request timeout, retries left 2
[ WARN] [1641480371.016490415]: CMD: Command 520 -- wait ack timeout
[ WARN] [1641480371.018437711]: VER: unicast request timeout, retries left 1
[ WARN] [1641480376.037921165]: CMD: Command 520 -- wait ack timeout
[ WARN] [1641480376.040334669]: VER: unicast request timeout, retries left 0
[ WARN] [1641480381.056068011]: CMD: Command 520 -- wait ack timeout
[ WARN] [1641480381.058163883]: VER: your FCU don't support AUTOPILOT_VERSION, switched to default capabilities
```

### Diagnostics

```
header:
  seq: 82
  stamp:
    secs: 1641480460
    nsecs: 448215822
  frame_id: ''
status:
  -
    level: 0
    name: "mavros: FCU connection"
    message: "connected"
    hardware_id: "udp://:14550@:14555/?ids=255,1"
    values:
      -
        key: "Received packets:"
        value: "12303"
      -
        key: "Dropped packets:"
        value: "0"
      -
        key: "Buffer overruns:"
        value: "0"
      -
        key: "Parse errors:"
        value: "0"
      -
        key: "Rx sequence number:"
        value: "1"
      -
        key: "Tx sequence number:"
        value: "0"
      -
        key: "Rx total bytes:"
        value: "450826"
      -
        key: "Tx total bytes:"
        value: "22121"
      -
        key: "Rx speed:"
        value: "4353.000000"
      -
        key: "Tx speed:"
        value: "210.000000"
  -
    level: 1
    name: "mavros: GPS"
    message: "No fix"
    hardware_id: "udp://:14550@:14555/?ids=255,1"
    values:
      -
        key: "Satellites visible"
        value: "5"
      -
        key: "Fix type"
        value: "1"
      -
        key: "EPH (m)"
        value: "0.00"
      -
        key: "EPV (m)"
        value: "0.00"
  -
    level: 0
    name: "mavros: Heartbeat"
    message: "Normal"
    hardware_id: "udp://:14550@:14555/?ids=255,1"
    values:
      -
        key: "Heartbeats since startup"
        value: "207"
      -
        key: "Frequency (Hz)"
        value: "2.000019"
      -
        key: "Vehicle type"
        value: "Quadrotor"
      -
        key: "Autopilot type"
        value: "ArduPilot"
      -
        key: "Mode"
        value: "STABILIZE"
      -
        key: "System status"
        value: "Active"
  -
    level: 0
    name: "mavros: System"
    message: "Normal"
    hardware_id: "udp://:14550@:14555/?ids=255,1"
    values:
      -
        key: "Sensor present"
        value: "0x00000000"
      -
        key: "Sensor enabled"
        value: "0x00000000"
      -
        key: "Sensor health"
        value: "0x00000000"
      -
        key: "CPU Load (%)"
        value: "0.0"
      -
        key: "Drop rate (%)"
        value: "0.0"
      -
        key: "Errors comm"
        value: "0"
      -
        key: "Errors count #1"
        value: "0"
      -
        key: "Errors count #2"
        value: "0"
      -
        key: "Errors count #3"
        value: "0"
      -
        key: "Errors count #4"
        value: "0"
  -
    level: 1
    name: "mavros: Battery"
    message: "Low voltage"
    hardware_id: "udp://:14550@:14555/?ids=255,1"
    values:
      -
        key: "Voltage"
        value: "0.00"
      -
        key: "Current"
        value: "0.0"
      -
        key: "Remaining"
        value: "94.0"
  -
    level: 1
    name: "mavros: 3DR Radio"
    message: "Low RSSI"
    hardware_id: "udp://:14550@:14555/?ids=255,1"
    values:
      -
        key: "RSSI"
        value: "0"
      -
        key: "RSSI (dBm)"
        value: "-127.0"
      -
        key: "Remote RSSI"
        value: "0"
      -
        key: "Remote RSSI (dBm)"
        value: "-127.0"
      -
        key: "Tx buffer (%)"
        value: "0"
      -
        key: "Noice level"
        value: "0"
      -
        key: "Remote noice level"
        value: "0"
      -
        key: "Rx errors"
        value: "0"
      -
        key: "Fixed"
        value: "0"
---
```

### Check ID

```
OK. I got messages from 1:1.

---
Received 1776 messages, from 1 addresses
sys:comp   list of messages
  1:1     0, 33, 1, 65, 74, 141, 109, 241, 242, 147, 24, 125, 30
```
