### ISSUE TITLE
Stuck in AUTO.TAKEOFF

### ISSUE THREAD

**Issue by DevJav** [mavlink/mavros#1730]
### Issue details

I'm developing a software to send certain commands to the autopilot but I'm having some issues because after taking off, made calling the takeoff srv, the mode stays in` AUTO.TAKEOFF`, and trying to change it with set_mode srv to `AUTO.LOITER` results in `CMD: Unexpected command 176, result 0`.

If I open QGroundControl, this problem is solved, but I'm planning in not using it.

I'm working with the Gazebo simulation.

### MAVROS version and platform

Mavros: 1.12.2
ROS: Melodic
Ubuntu: 18.04

### Autopilot type and version

[  ] ArduPilot
[ X ] PX4

### Diagnostics

```
header: 
  seq: 994
  stamp: 
    secs: 1649748314
    nsecs: 663453369
  frame_id: ''
status: 
  - 
    level: 0
    name: "mavros: FCU connection"
    message: "connected"
    hardware_id: "udp://:14540@127.0.0.1:14557"
    values: 
      - 
        key: "Received packets:"
        value: "58297"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "232"
      - 
        key: "Tx sequence number:"
        value: "0"
      - 
        key: "Rx total bytes:"
        value: "34000759"
      - 
        key: "Tx total bytes:"
        value: "775694"
      - 
        key: "Rx speed:"
        value: "37609.000000"
      - 
        key: "Tx speed:"
        value: "890.000000"
  - 
    level: 0
    name: "mavros: GPS"
    message: "3D fix"
    hardware_id: "udp://:14540@127.0.0.1:14557"
    values: 
      - 
        key: "Satellites visible"
        value: "10"
      - 
        key: "Fix type"
        value: "3"
      - 
        key: "EPH (m)"
        value: "0.00"
      - 
        key: "EPV (m)"
        value: "0.00"
  - 
    level: 0
    name: "mavros: Heartbeat"
    message: "Normal"
    hardware_id: "udp://:14540@127.0.0.1:14557"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "1355"
      - 
        key: "Frequency (Hz)"
        value: "0.965522"
      - 
        key: "Vehicle type"
        value: "Quadrotor"
      - 
        key: "Autopilot type"
        value: "PX4 Autopilot"
      - 
        key: "Mode"
        value: "AUTO.TAKEOFF"
      - 
        key: "System status"
        value: "Critical"
  - 
    level: 0
    name: "mavros: System"
    message: "Normal"
    hardware_id: "udp://:14540@127.0.0.1:14557"
    values: 
      - 
        key: "Sensor present"
        value: "0x9028002C"
      - 
        key: "Sensor enabled"
        value: "0x9020000C"
      - 
        key: "Sensor health"
        value: "0x902E002F"
      - 
        key: "3D magnetometer"
        value: "Ok"
      - 
        key: "absolute pressure"
        value: "Ok"
      - 
        key: "AHRS subsystem health"
        value: "Ok"
      - 
        key: "pre-arm check status. Always healthy when armed"
        value: "Ok"
      - 
        key: "CPU Load (%)"
        value: "46.0"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 0
    name: "mavros: Battery"
    message: "Normal"
    hardware_id: "udp://:14540@127.0.0.1:14557"
    values: 
      - 
        key: "Voltage"
        value: "15.10"
      - 
        key: "Current"
        value: "-1.0"
      - 
        key: "Remaining"
        value: "89.0"
  - 
    level: 0
    name: "mavros: Time Sync"
    message: "Normal"
    hardware_id: "udp://:14540@127.0.0.1:14557"
    values: 
      - 
        key: "Timesyncs since startup"
        value: "13560"
      - 
        key: "Frequency (Hz)"
        value: "10.000048"
      - 
        key: "Last RTT (ms)"
        value: "0.456415"
      - 
        key: "Mean RTT (ms)"
        value: "0.463200"
      - 
        key: "Last remote time (s)"
        value: "1363.660000000"
      - 
        key: "Estimated time offset (s)"
        value: "1649746950.987334490"

```

### Check ID

```
OK. I got messages from 1:1.

---
Received 6434 messages, from 1 addresses
sys:comp   list of messages
  1:1     0, 1, 2, 4, 8, 140, 141, 147, 24, 411, 30, 31, 32, 33, 36, 42, 74, 331, 83, 340, 85, 87, 230, 105, 111, 241, 242, 245

```
