### ISSUE TITLE
/mavros/cmd/command_int not working

### ISSUE THREAD

**Issue by JulienRineau** [mavlink/mavros#1750]
### Issue details

I am working on Jmavsim. I can took off successfully but when I try to run `rosservice call /mavros/cmd/command_int "{broadcast: false, frame: 1, command: 84, current: 0, autocontinue: 0, param1: 0.0, param2: 0.0, param3: 0.0, param4: 0.0, x: 3, y: 0, z: -1.0}"` nothing happened. I thought it was because I had to ignore some parameters and tried `rosservice call /mavros/cmd/command_int "{broadcast: false, frame: 4, command: 84, current: True, autocontinue: True,  x: 3, y: 0, z: 3}"` but again nothing happened. I however do received `success: True` back when I run the commands. Btw the drone stay in mode AUTO.TAKEOFF.

Is the service still working or did I missed something else ?

### MAVROS version and platform

Mavros: 1.13.0
ROS: Noetic
Ubuntu: 20.04

### Autopilot type and version

[  ] ArduPilot
[X] PX4

Version: ?3.7.1?

### Diagnostics

```
header: 
  seq: 2517
  stamp: 
    secs: 1654075738
    nsecs: 280233894
  frame_id: ''
status: 
  - 
    level: 0
    name: "mavros: FCU connection"
    message: "connected"
    hardware_id: "udp://:14550@localhost:14555"
    values: 
      - 
        key: "Received packets:"
        value: "40471"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "79"
      - 
        key: "Tx sequence number:"
        value: "0"
      - 
        key: "Rx total bytes:"
        value: "21029959"
      - 
        key: "Tx total bytes:"
        value: "1052709"
      - 
        key: "Rx speed:"
        value: "7117.000000"
      - 
        key: "Tx speed:"
        value: "460.000000"
  - 
    level: 0
    name: "mavros: GPS"
    message: "3D fix"
    hardware_id: "udp://:14550@localhost:14555"
    values: 
      - 
        key: "Satellites visible"
        value: "10"
      - 
        key: "Fix type"
        value: "3"
      - 
        key: "EPH (m)"
        value: "0.00"
      - 
        key: "EPV (m)"
        value: "0.00"
  - 
    level: 0
    name: "mavros: Heartbeat"
    message: "Normal"
    hardware_id: "udp://:14550@localhost:14555"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "1282"
      - 
        key: "Frequency (Hz)"
        value: "0.296341"
      - 
        key: "Vehicle type"
        value: "Quadrotor"
      - 
        key: "Autopilot type"
        value: "PX4 Autopilot"
      - 
        key: "Mode"
        value: "AUTO.TAKEOFF"
      - 
        key: "System status"
        value: "Critical"
  - 
    level: 0
    name: "mavros: System"
    message: "Normal"
    hardware_id: "udp://:14550@localhost:14555"
    values: 
      - 
        key: "Sensor present"
        value: "0x9028802C"
      - 
        key: "Sensor enabled"
        value: "0x9020800C"
      - 
        key: "Sensor health"
        value: "0x902E802F"
      - 
        key: "3D magnetometer"
        value: "Ok"
      - 
        key: "absolute pressure"
        value: "Ok"
      - 
        key: "motor outputs / control"
        value: "Ok"
      - 
        key: "AHRS subsystem health"
        value: "Ok"
      - 
        key: "pre-arm check status. Always healthy when armed"
        value: "Ok"
      - 
        key: "CPU Load (%)"
        value: "28.3"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 0
    name: "mavros: Battery"
    message: "Normal"
    hardware_id: "udp://:14550@localhost:14555"
    values: 
      - 
        key: "Voltage"
        value: "15.10"
      - 
        key: "Current"
        value: "-1.0"
      - 
        key: "Remaining"
        value: "77.0"
  - 
    level: 0
    name: "mavros: Time Sync"
    message: "Normal"
    hardware_id: "udp://:14550@localhost:14555"
    values: 
      - 
        key: "Timesyncs since startup"
        value: "50"
      - 
        key: "Frequency (Hz)"
        value: "10.133232"
      - 
        key: "Last RTT (ms)"
        value: "0.725619"
      - 
        key: "Mean RTT (ms)"
        value: "2.978607"
      - 
        key: "Last remote time (s)"
        value: "1367.820000000"
      - 
        key: "Estimated time offset (s)"
        value: "1654074369.945951462"
---

```

### Check ID

```
OK. I got messages from 1:1.

---
Received 2023 messages, from 1 addresses
sys:comp   list of messages
  1:1     0, 1, 8, 141, 147, 24, 411, 30, 31, 32, 33, 36, 74, 83, 340, 85, 87, 230, 111, 242, 245

```
