### ISSUE TITLE
Detect heartbeat from GCS

### ISSUE THREAD

**Issue by esharet** [mavlink/mavros#1768]
### Issue details

I'm trying to detect if I get TYPE_GCS heartbeat. How can I do it with mavros? I wonder if sys_status plugin may help but I didn't understand how to use it. 
Thank you,

### MAVROS version and platform

Mavros: 2.2.0
ROS: Foxy
Ubuntu: 20.04

### Autopilot type and version

[X] ArduPilot
[  ] PX4

Version: 4.2.2 

### Node logs

```
[mavros_node-1] [INFO] [1659267737.277853467] [mavros_node]: Starting mavros_node container
[mavros_node-1] [INFO] [1659267737.277910084] [mavros_node]: FCU URL: udp://:14551@14555
[mavros_node-1] [INFO] [1659267737.277916927] [mavros_node]: GCS URL: udp://@
[mavros_node-1] [INFO] [1659267737.277921854] [mavros_node]: UAS Prefix: /uas1
[mavros_node-1] [INFO] [1659267737.277925755] [mavros_node]: Starting mavros router node
[mavros_node-1] [INFO] [1659267737.280637353] [mavros_router]: Built-in SIMD instructions: SSE, SSE2
[mavros_node-1] [INFO] [1659267737.280725646] [mavros_router]: Built-in MAVLink package version: 2022.3.3
[mavros_node-1] [INFO] [1659267737.280731950] [mavros_router]: Known MAVLink dialects: common ardupilotmega ASLUAV AVSSUAS all development icarous matrixpilot paparazzi standard storm32 uAvionix ualberta
[mavros_node-1] [INFO] [1659267737.280736951] [mavros_router]: MAVROS Router started
[mavros_node-1] [INFO] [1659267737.280815828] [mavros_router]: Requested to add endpoint: type: 0, url: udp://:14551@14555
[mavros_node-1] [INFO] [1659267737.280990750] [mavros_router]: Endpoint link[1000] created
[mavros_node-1] [INFO] [1659267737.281970250] [mavros_router]: link[1000] opened successfully
[mavros_node-1] [INFO] [1659267737.282044631] [mavros_router]: Requested to add endpoint: type: 1, url: udp://@
[mavros_node-1] [INFO] [1659267737.282091129] [mavros_router]: Endpoint link[1001] created
[mavros_node-1] [INFO] [1659267737.282195402] [mavros_router]: link[1001] opened successfully
[mavros_node-1] [INFO] [1659267737.282230315] [mavros_router]: Requested to add endpoint: type: 2, url: /uas1
[mavros_node-1] [INFO] [1659267737.282284507] [mavros_router]: Endpoint link[1002] created
[mavros_node-1] [INFO] [1659267737.283167694] [mavros_router]: link[1002] opened successfully
[mavros_node-1] [INFO] [1659267737.283207972] [mavros_node]: Starting mavros uas node
[mavros_node-1] [INFO] [1659267737.314103229] [mavros]: UAS Executor started, threads: 12
[mavros_node-1] [INFO] [1659267737.327913996] [mavros]: Plugin actuator_control created
[mavros_node-1] [INFO] [1659267737.328178340] [mavros]: Plugin actuator_control initialized
[mavros_node-1] [INFO] [1659267737.340732781] [mavros]: Plugin adsb created
[mavros_node-1] [INFO] [1659267737.340912445] [mavros]: Plugin adsb initialized
[mavros_node-1] [INFO] [1659267737.343598249] [mavros]: Plugin altitude created
[mavros_node-1] [INFO] [1659267737.343722644] [mavros]: Plugin altitude initialized
[mavros_node-1] [INFO] [1659267737.346358893] [mavros]: Plugin cam_imu_sync created
[mavros_node-1] [INFO] [1659267737.346482003] [mavros]: Plugin cam_imu_sync initialized
[mavros_node-1] [INFO] [1659267737.349119995] [mavros]: Plugin camera created
[mavros_node-1] [INFO] [1659267737.349256402] [mavros]: Plugin camera initialized
[mavros_node-1] [INFO] [1659267737.355345225] [mavros]: Plugin command created
[mavros_node-1] [INFO] [1659267737.355483320] [mavros]: Plugin command initialized
[mavros_node-1] [INFO] [1659267737.358410431] [mavros]: Plugin companion_process_status created
[mavros_node-1] [INFO] [1659267737.358443127] [mavros]: Plugin companion_process_status initialized
[mavros_node-1] [INFO] [1659267737.362086590] [mavros]: Plugin debug_value created
[mavros_node-1] [INFO] [1659267737.362361229] [mavros]: Plugin debug_value initialized
[mavros_node-1] [INFO] [1659267737.364903317] [mavros_router]: link[1000] detected remote address 1.1
[mavros_node-1] [INFO] [1659267737.365181086] [mavros.distance_sensor]: DS: Plugin not configured!
[mavros_node-1] [INFO] [1659267737.365289551] [mavros]: Plugin distance_sensor created
[mavros_node-1] [INFO] [1659267737.365422924] [mavros]: Plugin distance_sensor initialized
[mavros_node-1] [INFO] [1659267737.369034730] [mavros]: Plugin esc_status created
[mavros_node-1] [INFO] [1659267737.369204456] [mavros]: Plugin esc_status initialized
[mavros_node-1] [INFO] [1659267737.372875069] [mavros]: Plugin esc_telemetry created
[mavros_node-1] [INFO] [1659267737.373120040] [mavros]: Plugin esc_telemetry initialized
[mavros_node-1] [INFO] [1659267737.379072694] [mavros]: Plugin fake_gps created
[mavros_node-1] [INFO] [1659267737.379116971] [mavros]: Plugin fake_gps initialized
[mavros_node-1] [INFO] [1659267737.388748764] [mavros]: Plugin ftp created
[mavros_node-1] [INFO] [1659267737.388883196] [mavros]: Plugin ftp initialized
[mavros_node-1] [INFO] [1659267737.394104245] [mavros]: Plugin geofence created
[mavros_node-1] [INFO] [1659267737.394427341] [mavros]: Plugin geofence initialized
[mavros_node-1] [INFO] [1659267737.403404763] [mavros]: Plugin global_position created
[mavros_node-1] [INFO] [1659267737.403647087] [mavros]: Plugin global_position initialized
[mavros_node-1] [INFO] [1659267737.407835064] [mavros]: Plugin gps_input created
[mavros_node-1] [INFO] [1659267737.407872274] [mavros]: Plugin gps_input initialized
[mavros_node-1] [INFO] [1659267737.412413849] [mavros]: Plugin gps_rtk created
[mavros_node-1] [INFO] [1659267737.412574912] [mavros]: Plugin gps_rtk initialized
[mavros_node-1] [INFO] [1659267737.418018852] [mavros]: Plugin gps_status created
[mavros_node-1] [INFO] [1659267737.418335248] [mavros]: Plugin gps_status initialized
[mavros_node-1] [INFO] [1659267737.426060819] [mavros]: Plugin hil created
[mavros_node-1] [INFO] [1659267737.426225184] [mavros]: Plugin hil initialized
[mavros_node-1] [INFO] [1659267737.431388857] [mavros]: Plugin home_position created
[mavros_node-1] [INFO] [1659267737.431519516] [mavros]: Plugin home_position initialized
[mavros_node-1] [INFO] [1659267737.438485008] [mavros]: Plugin imu created
[mavros_node-1] [INFO] [1659267737.438811812] [mavros]: Plugin imu initialized
[mavros_node-1] [INFO] [1659267737.446078350] [mavros]: Plugin landing_target created
[mavros_node-1] [INFO] [1659267737.446222229] [mavros]: Plugin landing_target initialized
[mavros_node-1] [INFO] [1659267737.454145037] [mavros]: Plugin local_position created
[mavros_node-1] [INFO] [1659267737.454345678] [mavros]: Plugin local_position initialized
[mavros_node-1] [INFO] [1659267737.462004623] [mavros]: Plugin log_transfer created
[mavros_node-1] [INFO] [1659267737.462206417] [mavros]: Plugin log_transfer initialized
[mavros_node-1] [INFO] [1659267737.467811582] [mavros]: Plugin mag_calibration_status created
[mavros_node-1] [INFO] [1659267737.468009572] [mavros]: Plugin mag_calibration_status initialized
[mavros_node-1] [INFO] [1659267737.473951149] [mavros]: Plugin manual_control created
[mavros_node-1] [INFO] [1659267737.474083290] [mavros]: Plugin manual_control initialized
[mavros_node-1] [INFO] [1659267737.480083526] [mavros]: Plugin mocap_pose_estimate created
[mavros_node-1] [INFO] [1659267737.480121312] [mavros]: Plugin mocap_pose_estimate initialized
[mavros_node-1] [INFO] [1659267737.487908771] [mavros]: Plugin mount_control created
[mavros_node-1] [INFO] [1659267737.488088268] [mavros]: Plugin mount_control initialized
[mavros_node-1] [INFO] [1659267737.493541162] [mavros]: Plugin nav_controller_output created
[mavros_node-1] [INFO] [1659267737.493678864] [mavros]: Plugin nav_controller_output initialized
[mavros_node-1] [INFO] [1659267737.499867000] [mavros]: Plugin obstacle_distance created
[mavros_node-1] [INFO] [1659267737.499902889] [mavros]: Plugin obstacle_distance initialized
[mavros_node-1] [INFO] [1659267737.506722719] [mavros]: Plugin odometry created
[mavros_node-1] [INFO] [1659267737.506891652] [mavros]: Plugin odometry initialized
[mavros_node-1] [INFO] [1659267737.513958383] [mavros]: Plugin onboard_computer_status created
[mavros_node-1] [INFO] [1659267737.513996774] [mavros]: Plugin onboard_computer_status initialized
[mavros_node-1] [INFO] [1659267737.523732564] [mavros]: Plugin param created
[mavros_node-1] [INFO] [1659267737.523885856] [mavros]: Plugin param initialized
[mavros_node-1] [INFO] [1659267737.530686863] [mavros]: Plugin play_tune created
[mavros_node-1] [INFO] [1659267737.530725240] [mavros]: Plugin play_tune initialized
[mavros_node-1] [INFO] [1659267737.539792012] [mavros]: Plugin px created
[mavros_node-1] [INFO] [1659267737.539949757] [mavros]: Plugin px initialized
[mavros_node-1] [INFO] [1659267737.549133566] [mavros]: Plugin rallypoint created
[mavros_node-1] [INFO] [1659267737.549332455] [mavros]: Plugin rallypoint initialized
[mavros_node-1] [INFO] [1659267737.557020905] [mavros]: Plugin rangefinder created
[mavros_node-1] [INFO] [1659267737.557181325] [mavros]: Plugin rangefinder initialized
[mavros_node-1] [INFO] [1659267737.566110945] [mavros]: Plugin rc_io created
[mavros_node-1] [INFO] [1659267737.566323560] [mavros]: Plugin rc_io initialized
[mavros_node-1] [INFO] [1659267737.575872153] [mavros]: Plugin setpoint_accel created
[mavros_node-1] [INFO] [1659267737.575914391] [mavros]: Plugin setpoint_accel initialized
[mavros_node-1] [INFO] [1659267737.586408584] [mavros]: Plugin setpoint_attitude created
[mavros_node-1] [INFO] [1659267737.586448029] [mavros]: Plugin setpoint_attitude initialized
[mavros_node-1] [INFO] [1659267737.596721840] [mavros]: Plugin setpoint_position created
[mavros_node-1] [INFO] [1659267737.596763869] [mavros]: Plugin setpoint_position initialized
[mavros_node-1] [INFO] [1659267737.610299327] [mavros]: Plugin setpoint_raw created
[mavros_node-1] [INFO] [1659267737.610534245] [mavros]: Plugin setpoint_raw initialized
[mavros_node-1] [INFO] [1659267737.626726770] [mavros]: Plugin setpoint_trajectory created
[mavros_node-1] [INFO] [1659267737.626784928] [mavros]: Plugin setpoint_trajectory initialized
[mavros_node-1] [INFO] [1659267737.638611763] [mavros]: Plugin setpoint_velocity created
[mavros_node-1] [INFO] [1659267737.638650750] [mavros]: Plugin setpoint_velocity initialized
[mavros_node-1] [INFO] [1659267737.659747657] [mavros]: Plugin sys_status created
[mavros_node-1] [INFO] [1659267737.660320343] [mavros]: Plugin sys_status initialized
[mavros_node-1] [INFO] [1659267737.672801261] [mavros.time]: TM: Timesync mode: MAVLINK
[mavros_node-1] [INFO] [1659267737.676481332] [mavros]: Plugin sys_time created
[mavros_node-1] [INFO] [1659267737.676674656] [mavros]: Plugin sys_time initialized
[mavros_node-1] [INFO] [1659267737.688379771] [mavros]: Plugin tdr_radio created
[mavros_node-1] [INFO] [1659267737.688569224] [mavros]: Plugin tdr_radio initialized
[mavros_node-1] [INFO] [1659267737.698806251] [mavros]: Plugin terrain created
[mavros_node-1] [INFO] [1659267737.698956141] [mavros]: Plugin terrain initialized
[mavros_node-1] [INFO] [1659267737.710865042] [mavros]: Plugin trajectory created
[mavros_node-1] [INFO] [1659267737.711023961] [mavros]: Plugin trajectory initialized
[mavros_node-1] [INFO] [1659267737.711040495] [mavros]: Plugin tunnel ignored
[mavros_node-1] [INFO] [1659267737.711048131] [mavros]: Plugin vfr_hud ignored
[mavros_node-1] [INFO] [1659267737.711055278] [mavros]: Plugin vibration ignored
[mavros_node-1] [INFO] [1659267737.723959567] [mavros]: Plugin vision_pose created
[mavros_node-1] [INFO] [1659267737.723998631] [mavros]: Plugin vision_pose initialized
[mavros_node-1] [INFO] [1659267737.724010561] [mavros]: Plugin vision_speed ignored
[mavros_node-1] [INFO] [1659267737.740029413] [mavros]: Plugin waypoint created
[mavros_node-1] [INFO] [1659267737.740280237] [mavros]: Plugin waypoint initialized
[mavros_node-1] [INFO] [1659267737.740299152] [mavros]: Plugin wheel_odomotry ignored
[mavros_node-1] [INFO] [1659267737.750519908] [mavros]: Plugin wind_estimation created
[mavros_node-1] [INFO] [1659267737.750716686] [mavros]: Plugin wind_estimation initialized
[mavros_node-1] [INFO] [1659267737.752082520] [mavros]: Built-in SIMD instructions: SSE, SSE2
[mavros_node-1] [INFO] [1659267737.752098722] [mavros]: Built-in MAVLink package version: 2022.3.3
[mavros_node-1] [INFO] [1659267737.752104237] [mavros]: Known MAVLink dialects: common ardupilotmega ASLUAV AVSSUAS all development icarous matrixpilot paparazzi standard storm32 uAvionix ualberta
[mavros_node-1] [INFO] [1659267737.752109461] [mavros]: MAVROS UAS via /uas1 started. MY ID 1.191, TARGET ID 1.1
[mavros_node-1] [INFO] [1659267737.862644935] [mavros.rc]: RC_CHANNELS message detected!
[mavros_node-1] [INFO] [1659267737.862791387] [mavros.imu]: IMU: Raw IMU message used.
[mavros_node-1] [WARN] [1659267737.862871974] [mavros.imu]: IMU: linear acceleration on RAW_IMU known on APM only.
[mavros_node-1] [WARN] [1659267737.862883203] [mavros.imu]: IMU: ~imu/data_raw stores unscaled raw acceleration report.
[mavros_node-1] [INFO] [1659267737.983349968] [mavros]: CON: Got HEARTBEAT, connected. FCU: ArduPilot
[mavros_node-1] [INFO] [1659267737.983501853] [mavros.mission]: WP: detected enable_partial_push: 1
[mavros_node-1] [INFO] [1659267738.124968459] [mavros.rc]: RC_CHANNELS message detected!
[mavros_node-1] [INFO] [1659267738.125104804] [mavros.imu]: IMU: Raw IMU message used.
[mavros_node-1] [INFO] [1659267738.648895384] [mavros_router]: link[1002] detected remote address 1.191
[mavros_node-1] [WARN] [1659267739.003677147] [mavros.cmd]: CMD: Unexpected command 520, result 0
[mavros_node-1] [INFO] [1659267739.003901384] [mavros.geofence]: GF: Using MISSION_ITEM_INT
[mavros_node-1] [INFO] [1659267739.003925568] [mavros.rallypoint]: RP: Using MISSION_ITEM_INT
[mavros_node-1] [INFO] [1659267739.003936153] [mavros.mission]: WP: Using MISSION_ITEM_INT
[mavros_node-1] [INFO] [1659267739.003950260] [mavros.sys]: VER: 1.1: Capabilities         0x000000000000f1ef
[mavros_node-1] [INFO] [1659267739.003965488] [mavros.sys]: VER: 1.1: Flight software:     04020000 (020262bf)
[mavros_node-1] [INFO] [1659267739.003974077] [mavros.sys]: VER: 1.1: Middleware software: 00000000 (        )
[mavros_node-1] [INFO] [1659267739.003981117] [mavros.sys]: VER: 1.1: OS software:         00000000 (        )
[mavros_node-1] [INFO] [1659267739.003990475] [mavros.sys]: VER: 1.1: Board hardware:      00000000
[mavros_node-1] [INFO] [1659267739.004000307] [mavros.sys]: VER: 1.1: VID/PID:             0000:0000
[mavros_node-1] [INFO] [1659267739.004009713] [mavros.sys]: VER: 1.1: UID:                 0000000000000000
```

### Diagnostics

```
header:
  stamp:
    sec: 1659267976
    nanosec: 285248362
  frame_id: ''
status:
- level: "\0"
  name: 'mavros: MAVROS UAS'
  message: connected
  hardware_id: uas:///uas1
  values: []
- level: "\0"
  name: 'mavros: GPS'
  message: 3D fix
  hardware_id: uas:///uas1
  values:
  - key: Satellites visible
    value: '10'
  - key: Fix type
    value: '6'
  - key: EPH (m)
    value: '1.21'
  - key: EPV (m)
    value: '2.00'
- level: "\0"
  name: 'mavros: System'
  message: Normal
  hardware_id: uas:///uas1
  values:
  - key: Sensor present
    value: '0x1330DC2F'
  - key: Sensor enabled
    value: '0x0320802F'
  - key: Sensor health
    value: '0x0330812F'
  - key: 3D gyro
    value: Ok
  - key: 3D accelerometer
    value: Ok
  - key: 3D magnetometer
    value: Ok
  - key: absolute pressure
    value: Ok
  - key: GPS
    value: Ok
  - key: motor outputs / control
    value: Ok
  - key: AHRS subsystem health
    value: Ok
  - key: Logging
    value: Ok
  - key: Battery
    value: Ok
  - key: CPU Load (%)
    value: '0.0'
  - key: Drop rate (%)
    value: '0.0'
  - key: Errors comm
    value: '0'
  - key: 'Errors count #1'
    value: '0'
  - key: 'Errors count #2'
    value: '0'
  - key: 'Errors count #3'
    value: '0'
  - key: 'Errors count #4'
    value: '0'
- level: "\0"
  name: 'mavros: Battery'
  message: Normal
  hardware_id: uas:///uas1
  values:
  - key: Voltage
    value: '12.59'
  - key: Current
    value: '0.0'
  - key: Remaining
    value: '89.0'
- level: "\0"
  name: 'mavros: Heartbeat'
  message: Normal
  hardware_id: uas:///uas1
  values:
  - key: Heartbeats since startup
    value: '239'
  - key: Frequency (Hz)
    value: '1.000000'
  - key: Vehicle type
    value: Ground rover
  - key: Autopilot type
    value: ArduPilot
  - key: Mode
    value: MANUAL
  - key: System status
    value: ACTIVE
```

### Check ID

```
Router topic: /uas1/mavlink_source, target: 1.1
OK. I got messages from 1.1.
---
Received 1518, from 1 addresses
address   list of messages
    1.1   0 (HEARTBEAT), 1 (SYS_STATUS), 129 (SCALED_IMU3), 2 (SYSTEM_TIME), 137 (SCALED_PRESSURE2), 147 (BATTERY_STATUS), 22 (PARAM_VALUE), 152, 24 (GPS_RAW_INT), 27 (RAW_IMU), 29 (SCALED_PRESSURE), 30 (ATTITUDE), 32 (LOCAL_POSITION_NED), 33 (GLOBAL_POSITION_INT), 34 (RC_CHANNELS_SCALED), 163, 36 (SERVO_OUTPUT_RAW), 164, 165, 42 (MISSION_CURRENT), 178, 65 (RC_CHANNELS), 193, 74 (VFR_HUD), 111 (TIMESYNC), 241 (VIBRATION), 116 (SCALED_IMU2), 125 (POWER_STATUS)```
