### ISSUE TITLE
/mavros/local_position/pose is negative of mavros/setpoint_raw/attitude when doing mavros gazebo SITL

### ISSUE THREAD

**Issue by Daidalos92** [mavlink/mavros#1823]
I am running a gazebo simulation using SITL with mavros. I send euler input and convert the desired attitude setpoint to quaternion using tf.transform. however, when checking the rostopic of the pose and setpoint sent, the uav orientation is the negative of what the raw attitude setpoints are. Is it due to the coordinate frames being misaligned? 
Also I occationally receive this timesync error. is it a cause of concern?

`ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.`

output from /mavros/local_position/pose

```
header: 
  seq: 160
  stamp: 
    secs: 1674723886
    nsecs: 931765232
  frame_id: "map"
pose: 
  position: 
    x: 11.8791685104
    y: -0.129774600267
    z: 0.109793841839
  orientation: 
    x: -0.173597563782
    y: -0.00244281553462
    z: -0.984764571499
    w: -0.00984044619032
```

output of mavros/setpoint_raw/attitude

```
header: 
  seq: 1509
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
type_mask: 0
orientation: 
  x: 0.173648177471
  y: 0.0
  z: 0.984807753047
  w: 0.0
body_rate: 
  x: 0.0
  y: 0.0
  z: 0.0
thrust: 0.5
```
