### ISSUE TITLE
PixHawk timestamp instead of ROS time

### ISSUE THREAD

**Issue by thedinuka** [mavlink/mavros#185]
I was looking at imu_pub.cpp and realized that imu/data_raw  topic is published with the header timestamp set to ROS::Time::now() 
(https://github.com/mavlink/mavros/blob/master/mavros/src/plugins/imu_pub.cpp#L250)

The MAVLINK_MSG_ID_HIGHRES_IMU message from PixHawk does contain a time_usec filed which actually represent the time at which the imu data was captured. For certain applications like for synchronizing a camera and IMU, it maybe useful to have that as the timestamp instead of the ros time. 

I'm wondering whether this would qualify as a new feature request? I could do a PR for this, but the change in the code is really simple anyway.

**Comment by mhkabir** [comment]
Hi, 
We have timesync working. I will be updating the plugins soon to take advantage of this. We synchronise Pixhawk timestamps to ROS time and vice-versa.
What you propose would not be ideal, as ROS wall time is calculated from Unix Epoch and Pixhawk time is calculated from boot.

**Comment by thedinuka** [comment]
@mhkabir timesync would be ideal, I agree. What sort of accuracies can you achieve with it?

**Comment by mhkabir** [comment]
We get microsecond precision.

**Comment by thedinuka** [comment]
ahh, excellent. would you be able to comment on when this will be available?

**Comment by mhkabir** [comment]
Pretty soon hopefully. Synchronisation works already (check system_time.cpp ) The plugins just need to be updated.

**Comment by thedinuka** [comment]
@mhkabir I'm still reading through system_time.cpp (actually  it's sys_time.cpp right?) but as a preliminary question, is the idea to maintain the difference between ros time and PixHawk time and then use that offset in other plugins to set the correct timestamp?

**Comment by mhkabir** [comment]
Yes

**Comment by vooon** [comment]
I testing PR #186.

Setup:
- Wandboard Quad with Ubuntu 14.04 and latest ROS for UbuntuARM
- Pixhawk with latest master

Results:
First run without custom `-m onboard` mode.
Got timsync, but strange timestamps:

*/mavros/imu/data*
```yaml
---
header: 
  seq: 4316
  stamp: 
    secs: 4294967295
    nsecs: 4294967295
  frame_id: fcu
orientation: 
  x: -0.0430093572484
  y: 0.00982332692738
  z: -0.307822874007
  w: 0.950420315269
orientation_covariance: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
angular_velocity: 
  x: 0.0105894114822
  y: -0.0485693067312
  z: -0.010234859772
angular_velocity_covariance: [1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07]
linear_acceleration: 
  x: 0.0641356706619
  y: -0.864281475544
  z: 10.0234670639
linear_acceleration_covariance: [8.999999999999999e-08, 0.0, 0.0, 0.0, 8.999999999999999e-08, 0.0, 0.0, 0.0, 8.999999999999999e-08]
---
header: 
  seq: 4317
  stamp: 
    secs: 4294967295
    nsecs: 4294967295
  frame_id: fcu
orientation: 
  x: -0.0430188834137
  y: 0.00986130963341
  z: -0.307839425409
  w: 0.950414129948
orientation_covariance: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
angular_velocity: 
  x: 0.00931540410966
  y: -0.0476437397301
  z: -0.00976792909205
angular_velocity_covariance: [1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07]
linear_acceleration: 
  x: 0.0641356706619
  y: -0.864281475544
  z: 10.0234670639
linear_acceleration_covariance: [8.999999999999999e-08, 0.0, 0.0, 0.0, 8.999999999999999e-08, 0.0, 0.0, 0.0, 8.999999999999999e-08]
---

```

*/diagnostics*
```yaml
  - 
    level: 0
    name: mavros: Time Sync
    message: Normal
    hardware_id: Mavlink
    values: 
      - 
        key: Events in window
        value: 100
      - 
        key: Events since startup
        value: 1361
      - 
        key: Duration of window (s)
        value: 10.007385
      - 
        key: Actual frequency (Hz)
        value: 9.992621
      - 
        key: Last dt (ms)
        value: 0.550172
      - 
        key: Mean dt (ms)
        value: -0.000695
      - 
        key: Last system time (s)
        value: 204.922809000
      - 
        key: Time offset (s)
        value: 1421389669.363838673
```
