### ISSUE TITLE
BUG: plugin_allowlist accepts garbage input without error

### ISSUE THREAD

**Issue by Ryanf55** [mavlink/mavros#2024]
# Expected Behavior

If you request plugins to load that don't exist, mavros should either print an error

# Actual behavior

No error is emitted, a garbage plugin name is silently discarded. This results in a typo in a plugin name resulting in not loading what you expect.

```yaml
/**:
  ros__parameters:
    plugin_allowlist:
       - 'sys_status'
       - 'sys_time'
       - 'garbage'
```

```
$ ros2 param dump /mavros/mavros
/mavros/mavros:
  ros__parameters:
    base_link_frame_id: base_link
    component_id: 191
    diagnostic_updater:
      period: 1.0
      use_fqn: false
    fcu_protocol: v2.0
    map_frame_id: map
    odom_frame_id: odom
    plugin_allowlist:
    - sys_status
    - sys_time
    - garbage
```
