### ISSUE TITLE
Not able to arm using telem2

### ISSUE THREAD

**Issue by Diamg** [mavlink/mavros#283]
Hi,

I'm using a raspberry 2 as onboard computer and I'm able to read the topic either from the usb as well as from the uart(rpi) to telem2(px4). The problem comes when sending an arming comand, it works with the us but not with the uart. 
The response are: 
$rosservice call /mavros/cmd/arming "value: true"
success: False
result: 4
$ rosrun mavros mavsafety arm
Request failed. Check mavros logs

On the px4.launch terminal there is no info message when it happens.

Moreover I put here the warnings I obtain on the mavros_node even though I think they don't have nothing to do.
```
[ WARN] [1430122958.486594299]: RAW_IMU: linear acceleration known on APM only
[ WARN] [1430122958.508094584]: TF to MSG: Quaternion Not Properly Normalized

[ WARN] [1430122972.703239245]: PR: request list timeout, retries left 2
[ WARN] [1430122972.740587117]: VER: request timeout, retries left 1
[ WARN] [1430122973.705465197]: PR: request list timeout, retries left 1
[ WARN] [1430122974.707253341]: PR: request list timeout, retries left 0
[ WARN] [1430122977.764099451]: VER: request timeout, retries left 0
[ WARN] [1430122982.789108852]: VER: your FCU don't support AUTOPILOT_VERSION, switched to default capabilities
```

The firmware I'm using is  ArduCopter V3.2.1

Thanks in advance

**Comment by vooon** [comment]
Please:

a. Update to 0.11.2 (yesterday release)
b. what launch script you used?
c. `rostopic echo -n1 /diagnostics`

Note: use triple ` for code blocks (read [github formatting page](https://guides.github.com/features/mastering-markdown/)).

**Comment by Diamg** [comment]
Hi,
a. mavros is updated.
b. I'm using:
```roslaunch mavros px4.launch```
c. 
```rostopic echo -n1 /diagnostics```
```
header: 
  seq: 284
  stamp: 
    secs: 1430218701
    nsecs: 929121105
  frame_id: ''
status: 
  - 
    level: 0
    name: mavros: FCU connection
    message: connected
    hardware_id: /dev/ttyAMA0:115200
    values: 
      - 
        key: Received packets:
        value: 708
      - 
        key: Dropped packets:
        value: 0
      - 
        key: Buffer overruns:
        value: 0
      - 
        key: Parse errors:
        value: 0
      - 
        key: Rx sequence number:
        value: 62
      - 
        key: Tx sequence number:
        value: 58
      - 
        key: Rx total bytes:
        value: 19296
      - 
        key: Tx total bytes:
        value: 73619
      - 
        key: Rx speed:
        value: 1059.000000
      - 
        key: Tx speed:
        value: 260.000000
  - 
    level: 0
    name: mavros: GPS
    message: 3D fix
    hardware_id: /dev/ttyAMA0:115200
    values: 
      - 
        key: Satellites visible
        value: 8
      - 
        key: Fix type
        value: 3
      - 
        key: EPH (m)
        value: 1.97
      - 
        key: EPV (m)
        value: Unknown
  - 
    level: 0
    name: mavros: Heartbeat
    message: Normal
    hardware_id: /dev/ttyAMA0:115200
    values: 
      - 
        key: Heartbeats since startup
        value: 20
      - 
        key: Frequency (Hz)
        value: 0.999110
      - 
        key: Vehicle type
        value: Octorotor
      - 
        key: Autopilot type
        value: ArduPilotMega
      - 
        key: Mode
        value: ALT_HOLD
      - 
        key: System status
        value: Standby
  - 
    level: 0
    name: mavros: System
    message: Normal
    hardware_id: /dev/ttyAMA0:115200
    values: 
      - 
        key: Sensor present
        value: 0x0060FC2F
      - 
        key: Sensor enabled
        value: 0x0060FC2F
      - 
        key: Sensor helth
        value: 0x0060FC2F
      - 
        key: Sensor 3D Gyro
        value: Ok
      - 
        key: Sensor 3D Accel
        value: Ok
      - 
        key: Sensor 3D Mag
        value: Ok
      - 
        key: Sensor Abs Pressure
        value: Ok
      - 
        key: Sensor GPS
        value: Ok
      - 
        key: Sensor Ang Rate Control
        value: Ok
      - 
        key: Sensor Attitude Stab
        value: Ok
      - 
        key: Sensor Yaw Position
        value: Ok
      - 
        key: Sensor Z/Alt Control
        value: Ok
      - 
        key: Sensor X/Y Pos Control
        value: Ok
      - 
        key: Sensor Motor Outputs
        value: Ok
      - 
        key: AHRS health
        value: Ok
      - 
        key: Terrain health
        value: Ok
      - 
        key: CPU Load (%)
        value: 55.9
      - 
        key: Drop rate (%)
        value: 0.0
      - 
        key: Errors comm
        value: 0
      - 
        key: Errors count #1
        value: 0
      - 
        key: Errors count #2
        value: 0
      - 
        key: Errors count #3
        value: 0
      - 
        key: Errors count #4
        value: 0
  - 
    level: 0
    name: mavros: Battery
    message: Normal
    hardware_id: /dev/ttyAMA0:115200
    values: 
      - 
        key: Voltage
        value: 16.54
      - 
        key: Current
        value: 0.4
      - 
        key: Remaining
        value: 99.0
  - 
    level: 2
    name: mavros: Time Sync
    message: No events recorded.
    hardware_id: /dev/ttyAMA0:115200
    values: 
      - 
        key: Timesyncs since startup
        value: 0
      - 
        key: Frequency (Hz)
        value: 0.000000
      - 
        key: Last dt (ms)
        value: 0.000000
      - 
        key: Mean dt (ms)
        value: 0.000000
      - 
        key: Last system time (s)
        value: 0.000000000
      - 
        key: Time offset (s)
        value: 0.000000000
---
```
