### ISSUE TITLE
/mavros/local_position/local taking data from two sources : 

### ISSUE THREAD

**Issue by Royalcheese** [mavlink/mavros#303]
It seems that fcu is publishing data in /mavros/local_position/local topic on mavros...
Here my results : 
```
---
header: 
  seq: 5635
  stamp: 
    secs: 0
    nsecs: 0
  frame_id: global
pose: 
  position: 
    x: 0.0
    y: 0.0
    z: 1.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
---
header: 
  seq: 5636
  stamp: 
    secs: 0
    nsecs: 0
  frame_id: global
pose: 
  position: 
    x: 0.0
    y: 0.0
    z: 1.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
---
header: 
  seq: 634
  stamp: 
    secs: 946690338
    nsecs: 752075264
  frame_id: local_origin
pose: 
  position: 
    x: -4.65935700049e-05
    y: 4.29840292782e-06
    z: 0.99997895956
  orientation: 
    x: 0.00168625889722
    y: -0.00584274381409
    z: 0.000856630700448
    w: 0.999981142352
---
header: 
  seq: 5637
  stamp: 
    secs: 0
    nsecs: 0
  frame_id: global
pose: 
  position: 
    x: 0.0
    y: 0.0
    z: 1.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
```

I don't want local position to be corrupted by the data the drone is sending.. and I didn't manage for now to fix it.. Any help would be nice, I'm a bit confused.
