### ISSUE TITLE
Offboard mode queries.

### ISSUE THREAD

**Issue by tanmayshankar** [mavlink/mavros#347]
Hello everyone, 

I am running the Pixhawk with an Odroid XU3 on my Hexcopter, I've got Ubuntu 12.04 / ROS Hydro set up on it. mavros, mavros-extras installed as binaries. I've been trying to get Offboard mode and setpoint position control to work for a while now, with no success. 

I create a custom C++ node that publishes geometry_msgs::PoseStamped messages onto several topics. I was unsure of what the topic name was for ROS Hydro, so I published it over "/mavros/setpoint_position/local", "/mavros/setpoint_position/local_position", "/mavros/setpoint/local_position". The rate of publishing is around 3 Hz. 

Here are the steps I followed - 
1) Launch px4.launch, with the baud rate and device ID adjusted to ttyUSB0 and 460800 instead of 57600, which works for me. 
2) Run the above C++ node to publish setpoints.
3) a) Arm the Hexcopter using an RC in manual mode.
    b) Flip the switches on the RC corresponding to offboard, and position control mode. 

This still doesn't work, the Hexcopter hovers in the same place when I tried this. I also tried running 
rosrun mavros mavsys mode -c OFFBOARD, instead of the RC, but it times out. 
I also tried running the setpoint_demo.py executable, with the same result. 
 
Any ideas on what could be going wrong? (Details below). 
My diagnostics mentions APM somewhere, and I2C errors, but I'm not sure what that means. 

My mavros says - Flight mode: POSCTL
Reset pos sp : (3,-6), (or something similar). 

On echoing /mavros/state, it says ARMED :True, GUIDED: True. 

/diagnostics is as follows:
```
header: 
  seq: 264
  stamp: 
    secs: 1437504141
    nsecs: 573507835
  frame_id: ''
status: 
  - 
    level: 0
    name: mavros: FCU connection
    message: connected
    hardware_id: Mavlink
    values: 
      - 
        key: Received packets:
        value: 9446
      - 
        key: Dropped packets:
        value: 0
      - 
        key: Buffer overruns:
        value: 0
      - 
        key: Parse errors:
        value: 0
      - 
        key: Rx sequence number:
        value: 58
      - 
        key: Tx sequence number:
        value: 0
  - 
    level: 0
    name: mavros: GPS
    message: 3D fix
    hardware_id: Mavlink
    values: 
      - 
        key: Satellites visible
        value: 8
      - 
        key: Fix type
        value: 3
      - 
        key: EPH (m)
        value: 2.40
      - 
        key: EPV (m)
        value: 2.47
  - 
    level: 0
    name: mavros: Heartbeat
    message: Normal
    hardware_id: Mavlink
    values: 
      - 
        key: Events in window
        value: 10
      - 
        key: Events since startup
        value: 258
      - 
        key: Duration of window (s)
        value: 10.009986
      - 
        key: Actual frequency (Hz)
        value: 0.999002
      - 
        key: MAV Type
        value: 13
      - 
        key: Autopilot type
        value: 12
      - 
        key: Autopilot base mode
        value: 0xD9
      - 
        key: Autopilot custom mode
        value: 0x00030000
      - 
        key: Autopilot system status
        value: 4
  - 
    level: 0
    name: mavros: System
    message: Normal
    hardware_id: Mavlink
    values: 
      - 
        key: Sensor present
        value: 0x00000000
      - 
        key: Sensor enabled
        value: 0x00000000
      - 
        key: Sensor helth
        value: 0x00000000
      - 
        key: CPU Load (%)
        value: 30.3
      - 
        key: Drop rate (%)
        value: 0.0
      - 
        key: Errors comm
        value: 0
      - 
        key: Errors count #1
        value: 0
      - 
        key: Errors count #2
        value: 0
      - 
        key: Errors count #3
        value: 0
      - 
        key: Errors count #4
        value: 0
  - 
    level: 0
    name: mavros: Battery
    message: Normal
    hardware_id: Mavlink
    values: 
      - 
        key: Voltage
        value: 15.73
      - 
        key: Current
        value: 0.0
      - 
        key: Remaining
        value: 73.0
  - 
    level: 2
    name: mavros: APM Memory
    message: No data
    hardware_id: Mavlink
    values: 
      - 
        key: Free memory (B)
        value: -1
      - 
        key: Heap top
        value: 0x0000
  - 
    level: 2
    name: mavros: APM Hardware
    message: No data
    hardware_id: Mavlink
    values: 
      - 
        key: Core voltage
        value: -1.000000
      - 
        key: I2C errors
        value: 0
---
```
