### ISSUE TITLE
rosbag recorder triggerd by arming

### ISSUE THREAD

**Issue by vooon** [mavlink/mavros#385]
I think it might be useful to start log recording on FCU arming.

**Comment by mhkabir** [comment]
I like it :dancer:
Ability to call custom rosbag record script would be nice as well. Till now, I had been manually doing this, but automation would be a plus.

**Comment by vooon** [comment]
I'm actually think to make custom `record` script. As i know it is python-based, so i can base on it.
Alternatively we may to run program, in that case we may automate "do at arming event" anything.

**Comment by meuchel** [comment]
Because rosbag is anyway a standalone program I like more the generic one to be able to run any program.
If already on track with a module for event triggered actions you should also think about other events which could trigger something. E.g. disarm or others.

**Comment by vooon** [comment]
I checked rosbag and found that `play` and `record` is native binaries.
So generic only. Next thing is on what stack to write: python or c++.

Proposed config:
```yaml
some_node: # only used in log
  event: armed # not sure that it needed, for now i only want armning
  action: run, stop # required, start on run, stop on disarm
  name: rosbag # optional, define node name
  restart: true # optional, restart? not sure that it'll be implemented soon
  output: log # optional, same as <node output="" />
  rosrun: rosbag record -a # like rosrun
some_script_1:
  event: armed
  shell: turn_off_wifi.sh # any executable, 
some_script_2:
  event: disarmed
  shell: turn_on_wifi.sh
```
