### ISSUE TITLE
installing ros-*-mavlink from source -> $ROSINSTALL does not exist

### ISSUE THREAD

**Issue by ChristophTobler** [mavlink/mavros#409]
https://github.com/mavlink/mavros/blob/master/mavros/README.md

catkin_make_isolated --install-space $ROSINSTALL --install -DCMAKE_BUILD_TYPE=Release

-> $ROSINSTALL should be replaced by (the beginning of?) $ROS_PACKAGE_PATH

**Comment by mhkabir** [comment]
> -> $ROSINSTALL should be replaced by (the beginning of?) $ROS_PACKAGE_PATH
Yep, that's correct.

As-such I'd recommend that you switch to the new catkin build tools, which is much more simpler to use, and you can directly build mavlink in the same workspace.

**Comment by vooon** [comment]
Not exactly `$ROS_PACKAGE_PATH` provide several paths: workspace, installation (+ possible another workspace).

`$ROSINSTALL` should be manually set to place where you want to install package.

But new catkin tool is much easier, simply place mavlink-gpb package and build.
```
$ rosinstall_generator --rosdistro jade mavlink
```
```yaml
- git:
    local-name: mavlink
    uri: https://github.com/mavlink/mavlink-gbp-release.git
    version: release/jade/mavlink/2015.10.10-0
```
