### ISSUE TITLE
PixHawk mavros Broadcast request timeout retries left 4

### ISSUE THREAD

**Issue by Tondy** [mavlink/mavros#631]
Hello

Having some issues with mavros and pixhawk.   After running

roslaunch mavros px4.launch error below appears I read around
but only came across pixhawk timestamp issue highlight. All the
time stamp blogs are not clear on step by step fixes or the issue
hope you can help

### Issue details

```
[ WARN] [1481526009.598878106]: VER: broadcast request timeout, retries left 4
[ WARN] [1481526010.597548940]: VER: broadcast request timeout, retries left 3
[ WARN] [1481526016.597896232]: VER: unicast request timeout, retries left 2
[ WARN] [1481526018.591265205]: PR: request list timeout, retries left 2
[ WARN] [1481526019.591693438]: PR: request list timeout, retries left 1
[ WARN] [1481526020.592750183]: PR: request list timeout, retries left 0
[ WARN] [1481526021.604779687]: VER: unicast request timeout, retries left 1
[ WARN] [1481526026.611953343]: VER: unicast request timeout, retries left 0
[ WARN] [1481526031.619284758]: VER: your FCU don't support AUTOPILOT_VERSION, switched to 
```

### MAVROS version and platform

Mavros: 
ROS: Indigo
Ubuntu: 16.04

### Autopilot type and version

APM: Copter
Version: 3.3.3

### Node logs

```
copy output of mavros_node. Usually console where you run roslaunch
```

### Diagnostics

```
place here result of:
rostopic echo -n1 /diagnostics
odroid@odroid:~/aidrone$ rostopic echo -n1 /diagnostics
header: 
  seq: 21
  stamp: 
    secs: 1481526027
    nsecs: 677224952
  frame_id: ''
status: 
  - 
    level: 0
    name: mavros: FCU connection
    message: connected
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Received packets:
        value: 21
      - 
        key: Dropped packets:
        value: 0
      - 
        key: Buffer overruns:
        value: 0
      - 
        key: Parse errors:
        value: 0
      - 
        key: Rx sequence number:
        value: 108
      - 
        key: Tx sequence number:
        value: 251
      - 
        key: Rx total bytes:
        value: 357
      - 
        key: Tx total bytes:
        value: 5867
      - 
        key: Rx speed:
        value: 34.000000
      - 
        key: Tx speed:
        value: 475.000000
  - 
    level: 2
    name: mavros: GPS
    message: No satellites
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Satellites visible
        value: 0
      - 
        key: Fix type
        value: 0
      - 
        key: EPH (m)
        value: Unknown
      - 
        key: EPV (m)
        value: Unknown
  - 
    level: 0
    name: mavros: Heartbeat
    message: Normal
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Heartbeats since startup
        value: 21
      - 
        key: Frequency (Hz)
        value: 0.999963
      - 
        key: Vehicle type
        value: Quadrotor
      - 
        key: Autopilot type
        value: ArduPilotMega
      - 
        key: Mode
        value: STABILIZE
      - 
        key: System status
        value: Standby
  - 
    level: 0
    name: mavros: System
    message: Normal
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Sensor present
        value: 0x00000000
      - 
        key: Sensor enabled
        value: 0x00000000
      - 
        key: Sensor helth
        value: 0x00000000
      - 
        key: CPU Load (%)
        value: 0.0
      - 
        key: Drop rate (%)
        value: 0.0
      - 
        key: Errors comm
        value: 0
      - 
        key: Errors count #1
        value: 0
      - 
        key: Errors count #2
        value: 0
      - 
        key: Errors count #3
        value: 0
      - 
        key: Errors count #4
        value: 0
  - 
    level: 2
    name: mavros: Battery
    message: No data
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Voltage
        value: -1.00
      - 
        key: Current
        value: 0.0
      - 
        key: Remaining
        value: 0.0
  - 
    level: 2
    name: mavros: Time Sync
    message: No events recorded.
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Timesyncs since startup
        value: 0
      - 
        key: Frequency (Hz)
        value: 0.000000
      - 
        key: Last dt (ms)
        value: 0.000000
      - 
        key: Mean dt (ms)
        value: 0.000000
      - 
        key: Last system time (s)
        value: 0.000000000
      - 
        key: Time offset (s)
        value: 0.000000000
---
```

### Check ID

```
rosrun mavros checkid

OK. I got messages from 1:1.

---
Received 15 messages, from 1 addresses
sys:comp   list of messages
  1:1     0

```
