### ISSUE TITLE
can't get into 

### ISSUE THREAD

**Issue by cs147** [mavlink/mavros#668]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

when trying to get into the nuttx shell via: `./Tools/mavlink_shell.py /dev/ttyACM0 --baudrate 9600`

while the mavros node is running (ie we've done `roslaunch mavros px4.launch`)

mavros instantly dies when we try to get into the shell. Or if I'm in the shell and then launch mavros/px4, then the shell dies.

### MAVROS version and platform

Mavros: 0.18.7
ROS: Indigo
Ubuntu: 14.04

### Autopilot type and version

[  ] ArduPilot
[X] PX4

Version: 1.5.5

### Node logs

```
[ERROR] [1488329637.890963490]: serial0: receive: End of file
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
================================================================================REQUIRED process [mavros-1] has died!
process has died [pid 7057, exit code -6, cmd /home/quadlab/ros_ws_kinetic_src/devel/lib/mavros/mavros_node /vicon/Pelican_Landing/Pelican_Landing:=/mavros/mocap/tf __name:=mavros __log:=/home/quadlab/.ros/log/ac66d0ea-fe18-11e6-a434-001e063056a5/mavros-1.log].
log file: /home/quadlab/.ros/log/ac66d0ea-fe18-11e6-a434-001e063056a5/mavros-1*.log
Initiating shutdown!
================================================================================
[mavros-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```

### Diagnostics

```
header: 
  seq: 10
  stamp: 
    secs: 1488329955
    nsecs: 297649403
  frame_id: ''
status: 
  - 
    level: 0
    name: mavros: FCU connection
    message: connected
    hardware_id: /dev/ttyACM0:9600
    values: 
      - 
        key: Received packets:
        value: 345
      - 
        key: Dropped packets:
        value: 0
      - 
        key: Buffer overruns:
        value: 0
      - 
        key: Parse errors:
        value: 0
      - 
        key: Rx sequence number:
        value: 209
      - 
        key: Tx sequence number:
        value: 78
      - 
        key: Rx total bytes:
        value: 6650
      - 
        key: Tx total bytes:
        value: 1852
      - 
        key: Rx speed:
        value: 34.000000
      - 
        key: Tx speed:
        value: 397.000000
  - 
   level: 2
    name: mavros: GPS
    message: No satellites
    hardware_id: /dev/ttyACM0:9600
    values: 
      - 
        key: Satellites visible
        value: 0
      - 
        key: Fix type
        value: 0
      - 
        key: EPH (m)
        value: Unknown
      - 
        key: EPV (m)
        value: Unknown
  - 
    level: 0
    name: mavros: Heartbeat
    message: Normal
    hardware_id: /dev/ttyACM0:9600
    values: 
      - 
        key: Heartbeats since startup
        value: 7
      - 
        key: Frequency (Hz)
        value: 1.064927
      - 
        key: Vehicle type
        value: Quadrotor
      - 
        key: Autopilot type
        value: ArduPilotMega / ArduCopter
      - 
        key: Mode
        value: STABILIZE
      - 
        key: System status
        value: Standby
  - 
    level: 0
    name: mavros: System
    message: Normal
    hardware_id: /dev/ttyACM0:9600
    values: 
      - 
        key: Sensor present
        value: 0x00000000
      - 
        key: Sensor enabled
        value: 0x00000000
      - 
        key: Sensor helth
        value: 0x00000000
      - 
        key: CPU Load (%)
        value: 0.0
      - 
        key: Drop rate (%)
        value: 0.0
      - 
        key: Errors comm
        value: 0
      - 
        key: Errors count #1
        value: 0
      - 
        key: Errors count #2
        value: 0
      - 
        key: Errors count #3
        value: 0
      - 
        key: Errors count #4
        value: 0
 - 
    level: 2
    name: mavros: Battery
    message: No data
    hardware_id: /dev/ttyACM0:9600
    values: 
      - 
        key: Voltage
        value: -1.00
      - 
        key: Current
        value: 0.0
      - 
        key: Remaining
        value: 0.0
  - 
    level: 2
    name: mavros: Time Sync
    message: No events recorded.
    hardware_id: /dev/ttyACM0:9600
    values: 
      - 
        key: Timesyncs since startup
        value: 0
      - 
        key: Frequency (Hz)
        value: 0.000000
      - 
        key: Last dt (ms)
        value: 0.000000
      - 
        key: Mean dt (ms)
        value: 0.000000
      - 
        key: Last system time (s)
        value: 0.000000000
      - 
        key: Time offset (s)
        value: 0.000000000

```

### Check ID

```
OK. I got messages from 1:1.

---
Received 766 messages, from 1 addresses
sys:comp   list of messages
  1:1     0, 44, 77, 148, 22, 253

```
