### ISSUE TITLE
Custom mavlink message not received by mavros

### ISSUE THREAD

**Issue by Ramomrito** [mavlink/mavros#677]
### Issue details

Hello,

For the past three days I have been trying with no success to send my custom mavlink message to my ros network via mavros. I have looked at similiar issues #657  #166 , but they have not solved my problem. I have tried everything from adding my message to the normal common dialect, to creating my own dialect, but for some reason the handler function in my plugin is not executed when it takes my custom message as an argument.

If I however use another message in the common dialect (under 255 id ... mavlink 1.0?), my handle function works all fine. The compiler is not complaining about my message because I have the message definition in the mavlink package common.xml.

I have verified that my message is being sent from the pixhawk, and for clarification I used the dev.px4.io guide to set this all up.

Right now I am truly clueless as to why my message is not being received by mavros and would appreciate any help

### MAVROS version and platform

Mavros: 0.18.7
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[  ] ArduPilot
[ x ] PX4
### Node logs

Launches fine and loads my plugin!

### Diagnostics

```
header: 
  seq: 19
  stamp: 
    secs: 1489599977
    nsecs: 396413265
  frame_id: ''
status: 
  - 
    level: 0
    name: mavros: FCU connection
    message: connected
    hardware_id: udp://:14540@127.0.0.1:14557
    values: 
      - 
        key: Received packets:
        value: 7821
      - 
        key: Dropped packets:
        value: 0
      - 
        key: Buffer overruns:
        value: 0
      - 
        key: Parse errors:
        value: 0
      - 
        key: Rx sequence number:
        value: 156
      - 
        key: Tx sequence number:
        value: 100
      - 
        key: Rx total bytes:
        value: 337240
      - 
        key: Tx total bytes:
        value: 9239
      - 
        key: Rx speed:
        value: 41952.000000
      - 
        key: Tx speed:
        value: 835.000000
  - 
    level: 0
    name: mavros: GPS
    message: 3D fix
    hardware_id: udp://:14540@127.0.0.1:14557
    values: 
      - 
        key: Satellites visible
        value: 10
      - 
        key: Fix type
        value: 3
      - 
        key: EPH (m)
        value: 0.00
      - 
        key: EPV (m)
        value: 0.00
  - 
    level: 0
    name: mavros: Heartbeat
    message: Normal
    hardware_id: udp://:14540@127.0.0.1:14557
    values: 
      - 
        key: Heartbeats since startup
        value: 15
      - 
        key: Frequency (Hz)
        value: 1.000013
      - 
        key: Vehicle type
        value: Quadrotor
      - 
        key: Autopilot type
        value: PX4 Autopilot
      - 
        key: Mode
        value: AUTO.RTL
      - 
        key: System status
        value: Standby
  - 
    level: 0
    name: mavros: System
    message: Normal
    hardware_id: udp://:14540@127.0.0.1:14557
    values: 
      - 
        key: Sensor present
        value: 0x00000000
      - 
        key: Sensor enabled
        value: 0x00000000
      - 
        key: Sensor helth
        value: 0x00000000
      - 
        key: CPU Load (%)
        value: 0.0
      - 
        key: Drop rate (%)
        value: 0.0
      - 
        key: Errors comm
        value: 0
      - 
        key: Errors count #1
        value: 0
      - 
        key: Errors count #2
        value: 0
      - 
        key: Errors count #3
        value: 0
      - 
        key: Errors count #4
        value: 0
  - 
    level: 0
    name: mavros: Battery
    message: Normal
    hardware_id: udp://:14540@127.0.0.1:14557
    values: 
      - 
        key: Voltage
        value: 12.15
      - 
        key: Current
        value: -1.0
      - 
        key: Remaining
        value: 100.0
  - 
    level: 0
    name: mavros: Time Sync
    message: Normal
    hardware_id: udp://:14540@127.0.0.1:14557
    values: 
      - 
        key: Timesyncs since startup
        value: 156
      - 
        key: Frequency (Hz)
        value: 10.000138
      - 
        key: Last dt (ms)
        value: 0.019910
      - 
        key: Mean dt (ms)
        value: -0.000020
      - 
        key: Last system time (s)
        value: 16.850916000
      - 
        key: Time offset (s)
        value: 1489599960.528765917
---
```

### Check ID

OK. I got messages from 1:1.
```
---
Received 6089 messages, from 1 addresses
sys:comp   list of messages
  1:1     0, 1, 2, 140, 141, 147, 24, 30, 31, 32, 33, 74, 76, 83, 85, 87, 230, 231, 105, 111, 241, 242, 245, 253
```
No Surprise... my ID is not there
