### ISSUE TITLE
SITL Guided mode rejects nav commands: result 3

### ISSUE THREAD

**Issue by fbalaban** [mavlink/mavros#712]
### Issue details

ROSpy script to change to guided mode and then send nav commands to coordinates. It changes to guided mode (SetMode) but all commands with either CommandLong or CommandInt are rejected APM Planner msg: (FAILURE: Unsupported CMD: 16) 
mavlink msg:  Got MAVLink msg: COMMAND_ACK {command : 16, result : 3}

### MAVROS version and platform

Mavros: 0.18.7
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[ x] ArduPilot
[  ] PX4

ArduPlane
Version: 3.6.0

### Node logs

```
no message on mavros console 
```

### Diagnostics

```
header: 
  seq: 94
  stamp: 
    secs: 1494875298
    nsecs: 810423669
  frame_id: ''
status: 
  - 
    level: 0
    name: mavros1: FCU connection
    message: connected
    hardware_id: udp://localhost:14552@/
    values: 
      - 
        key: Received packets:
        value: 12818
      - 
        key: Dropped packets:
        value: 0
      - 
        key: Buffer overruns:
        value: 0
      - 
        key: Parse errors:
        value: 0
      - 
        key: Rx sequence number:
        value: 106
      - 
        key: Tx sequence number:
        value: 126
      - 
        key: Rx total bytes:
        value: 434673
      - 
        key: Tx total bytes:
        value: 2263
      - 
        key: Rx speed:
        value: 3497.000000
      - 
        key: Tx speed:
        value: 17.000000
  - 
    level: 0
    name: mavros1: GPS
    message: 3D fix
    hardware_id: udp://localhost:14552@/
    values: 
      - 
        key: Satellites visible
        value: 10
      - 
        key: Fix type
        value: 3
      - 
        key: EPH (m)
        value: 1.21
      - 
        key: EPV (m)
        value: 2.00
  - 
    level: 0
    name: mavros1: Heartbeat
    message: Normal
    hardware_id: udp://localhost:14552@/
    values: 
      - 
        key: Heartbeats since startup
        value: 116
      - 
        key: Frequency (Hz)
        value: 0.999939
      - 
        key: Vehicle type
        value: Fixed wing aircraft
      - 
        key: Autopilot type
        value: ArduPilotMega / ArduCopter
      - 
        key: Mode
        value: GUIDED
      - 
        key: System status
        value: Active
  - 
    level: 2
    name: mavros1: System
    message: Sensor helth
    hardware_id: udp://localhost:14552@/
    values: 
      - 
        key: Sensor present
        value: 0x0061FC3F
      - 
        key: Sensor enabled
        value: 0x0061FC3F
      - 
        key: Sensor helth
        value: 0x0031FC3F
      - 
        key: 3D gyro
        value: Ok
      - 
        key: 3D accelerometer
        value: Ok
      - 
        key: 3D magnetometer
        value: Ok
      - 
        key: absolute pressure
        value: Ok
      - 
        key: differential pressure
        value: Ok
      - 
        key: GPS
        value: Ok
      - 
        key: 3D angular rate control
        value: Ok
      - 
        key: attitude stabilization
        value: Ok
      - 
        key: yaw position
        value: Ok
      - 
        key: z/altitude control
        value: Ok
      - 
        key: x/y position control
        value: Ok
      - 
        key: motor outputs / control
        value: Ok
      - 
        key: rc receiver
        value: Ok
      - 
        key: AHRS subsystem health
        value: Ok
      - 
        key: Terrain subsystem health
        value: Fail
      - 
        key: CPU Load (%)
        value: 0.0
      - 
        key: Drop rate (%)
        value: 0.0
      - 
        key: Errors comm
        value: 0
      - 
        key: Errors count #1
        value: 0
      - 
        key: Errors count #2
        value: 0
      - 
        key: Errors count #3
        value: 0
      - 
        key: Errors count #4
        value: 0
  - 
    level: 0
    name: mavros1: Battery
    message: Normal
    hardware_id: udp://localhost:14552@/
    values: 
      - 
        key: Voltage
        value: 12.44
      - 
        key: Current
        value: 10.5
      - 
        key: Remaining
        value: 87.0

```

### Check ID

```
WARNING: /mavros/target_system_id not set. Used default value: 1
WARNING: /mavros/target_component_id not set. Used default value: 1
NOTE: Target parameters may be unset, but that may be result of incorrect --mavros-ns option.Double check results!
OK. I got messages from 1:1.

---
Received 1492 messages, from 1 addresses
sys:comp   list of messages
  1:1     0, 1, 2, 133, 193, 136, 152, 22, 150, 24, 27, 29, 30, 32, 33, 35, 164, 165, 168, 42, 174, 178, 182, 62, 65, 74, 163, 87, 36, 241, 116, 125

```
