### ISSUE TITLE
mavros/setpoint_position/local : Not working

### ISSUE THREAD

**Issue by b-rohit** [mavlink/mavros#729]
### question details

I want to send mocap position data to pixhawk. I wrote a simple program based on [https://dev.px4.io/en/ros/mavros_offboard.html](url). my source code is here [https://github.com/b-rohit/offboardnav](url). 
I have tested it in Gazebo simulation environment and It works fine. I want to emulate the same on quacopter based on pixhawk. I followed the tutorial [https://dev.px4.io/en/ros/external_position_estimation.html](url). when I run my program it arms the copter but disarm automatically after 5-6 sec and arm again ... It subscribes to "mavros/local_position/pose" topic to get current position, but the callback for the topic never get called. 
I keep getting following error 
[ERROR] [1497439390.804899443]: FCU: Failsafe enabled: no RC and no offboard
[ INFO] [1497439391.052993584]: FCU: Failsafe mode enabled
[ WARN] [1497439391.072776041]: PR: request param #79 timeout, retries left 1, and 584 params still missing
[ INFO] [1497439391.091944381]: FCU: Failsafe mode disabled
when I try to change flight mode to offboard using rc controller than I get below error message> 
[ERROR] [1497366588.498711872]: FCU: main state transition denied 

### MAVROS version and platform

Mavros: 0.19.0
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[X ] PX4

### Node logs

```
copy output of mavros_node. Usually console where you run roslaunch
```

### Diagnostics

```
place here result of:
rostopic echo -n1 /diagnostics
```
```
header: 
  seq: 106
  stamp: 
    secs: 1497439460
    nsecs: 791990964
  frame_id: ''
status: 
  - 
    level: 0
    name: mavros: FCU connection
    message: connected
    hardware_id: /dev/ttyUSB0
    values: 
      - 
        key: Received packets:
        value: 3816
      - 
        key: Dropped packets:
        value: 0
      - 
        key: Buffer overruns:
        value: 0
      - 
        key: Parse errors:
        value: 0
      - 
        key: Rx sequence number:
        value: 80
      - 
        key: Tx sequence number:
        value: 35
      - 
        key: Rx total bytes:
        value: 127416
      - 
        key: Tx total bytes:
        value: 111802
      - 
        key: Rx speed:
        value: 1198.000000
      - 
        key: Tx speed:
        value: 3146.000000
  - 
    level: 2
    name: mavros: GPS
    message: No satellites
    hardware_id: /dev/ttyUSB0
    values: 
      - 
        key: Satellites visible
        value: 0
      - 
        key: Fix type
        value: 0
      - 
        key: EPH (m)
        value: 99.99
      - 
        key: EPV (m)
        value: 99.99
  - 
    level: 0
    name: mavros: Heartbeat
    message: Normal
    hardware_id: /dev/ttyUSB0
    values: 
      - 
        key: Heartbeats since startup
        value: 124
      - 
        key: Frequency (Hz)
        value: 1.039986
      - 
        key: Vehicle type
        value: Quadrotor
      - 
        key: Autopilot type
        value: PX4 Autopilot
      - 
        key: Mode
        value: OFFBOARD
      - 
        key: System status
        value: Standby
  - 
    level: 0
    name: mavros: System
    message: Normal
    hardware_id: /dev/ttyUSB0
    values: 
      - 
        key: Sensor present
        value: 0x00000000
      - 
        key: Sensor enabled
        value: 0x00000000
      - 
        key: Sensor helth
        value: 0x00000000
      - 
        key: CPU Load (%)
        value: 33.3
      - 
        key: Drop rate (%)
        value: 0.0
      - 
        key: Errors comm
        value: 0
      - 
        key: Errors count #1
        value: 0
      - 
        key: Errors count #2
        value: 0
      - 
        key: Errors count #3
        value: 0
      - 
        key: Errors count #4
        value: 0
  - 
    level: 0
    name: mavros: Battery
    message: Normal
    hardware_id: /dev/ttyUSB0
    values: 
      - 
        key: Voltage
        value: 15.73
      - 
        key: Current
        value: 0.3
      - 
        key: Remaining
        value: 100.0
  - 
    level: 2
    name: mavros: Time Sync
    message: No events recorded.
    hardware_id: /dev/ttyUSB0
    values: 
      - 
        key: Timesyncs since startup
        value: 0
      - 
        key: Frequency (Hz)
        value: 0.000000
      - 
        key: Last dt (ms)
        value: -6.765325
      - 
        key: Mean dt (ms)
        value: 0.000000
      - 
        key: Last system time (s)
        value: 326.074343000
      - 
        key: Time offset (s)
        value: 1497439134.691754580
  - 
    level: 0
    name: mavros: 3DR Radio
    message: Normal
    hardware_id: /dev/ttyUSB0
    values: 
      - 
        key: RSSI
        value: 193
      - 
        key: RSSI (dBm)
        value: -25.4
      - 
        key: Remote RSSI
        value: 192
      - 
        key: Remote RSSI (dBm)
        value: -25.9
      - 
        key: Tx buffer (%)
        value: 47
      - 
        key: Noice level
        value: 60
      - 
        key: Remote noice level
        value: 64
      - 
        key: Rx errors
        value: 0
      - 
        key: Fixed
        value: 0
```

### Check ID

```
rosrun mavros checkid
```
`OK. I got messages from 1:1.

---
Received 557 messages, from 15 addresses
sys:comp   list of messages
 62:187   204
  1:66    49
 152:51    68
 69:95    83
  0:186   2
 254:9     163
  1:80    87
 51:68    109, 166
  1:24    106
  1:82    67
  0:0     0
  1:0     0
 134:17    186
  1:190   11
  1:1     0, 1, 2, 128, 147, 22, 24, 30, 36, 44, 181, 74, 77, 82, 83, 84, 86, 87, 100, 105, 111, 245
`
