### ISSUE TITLE
GPS Coordinates Not Shown Mavros

### ISSUE THREAD

**Issue by galadriel123** [mavlink/mavros#733]
My GPS unit works fine and I definitely have a GPS fix. I just checked it using mission planner. But whenever I rostopic echo /mavros/global_position/global I don't get any output and the launch session shows

```
[ INFO] [1497345919.615880554]: HP: requesting home position
[ INFO] [1497345929.615855895]: HP: requesting home position
[ INFO] [1497345939.615256971]: HP: requesting home position
[ INFO] [1497345949.615621527]: HP: requesting home position
[ INFO] [1497345959.615650670]: HP: requesting home position
[ INFO] [1497345969.615705906]: HP: requesting home position
```

**Comment by vooon** [comment]
Please follow [template](https://github.com/mavlink/mavros/blob/master/.github/ISSUE_TEMPLATE).

Does param download succeed? Did you tried to setup streams (`rosrun mavros mavsys rate --all 10`)?

**Comment by galadriel123** [comment]
@vooon 
Yeah. I am able to get mavros parameters and set them. I tried rostopic echo /diagnostics  and got the following. It says no satellites are visible but it clearly has a GPS fix in the mission planner. This is driving me crazy. Please help 
```
    level: 2
    name: mavros: GPS
    message: No satellites
    hardware_id: /dev/ttyAMA0:57600
    values:
      -
        key: Satellites visible
        value: 0
      -
        key: Fix type
        value: 0
      -
        key: EPH (m)
        value: Unknown
      -
        key: EPV (m)
        value: Unknown
  -
```
