### ISSUE TITLE
EKF measurement timeout when publishing pose to /mavros/vision_pose/pose

### ISSUE THREAD

**Issue by Roman-** [mavlink/mavros#782]
Hello,
I am using a Pixhawk with PX4 firmware and gazebo simulator, ekf2 as the state/pose estimator.
I want to use aruco fiducial markers for vision pose estimation. My ROS node publishes estimated coordinates to `/mavros/vision_pose/pose` topic. Here's an example of the message:
```
header: 
  seq: 25595
  stamp: 
    secs: 633445690
    nsecs: 321158808
  frame_id: fcu
pose: 
  position: 
    x: -5.8058299648
    y: 0.165404601647
    z: 4.50232891986
  orientation: 
    x: 0.00249907606208
    y: 0.000708453209019
    z: 0.0138610026572
    w: -0.999900600617
```

For testing vision-based navigation in the gazebo simulator, I do the following:
- on my laptop, launch px4, gazebo and mavros
- set `EKF2_AID_MASK` to 1 to enable GPS pose estimation and disable vision
- arm, enable POSCTL mode, takeoff and hover where the copter's front camera can see the markers in the simulated world
- turn on ros node that starts publishing to /mavros/vision_pose/pose
- echoing these topics to ensure they're posting approximately the same things:
    `/mavros/local_position/pose`
    `/mavros/vision_pose/pose`
- set `EKF2_AID_MASK` to 8 to disable GPS pose estimation and enable vision

Here is an example of two messages from these two topics obtained in about the same time:
```
header:  
  seq: 25595
  stamp: 
    secs: 633445690
    nsecs: 321158808
  frame_id: fcu
pose: 
  position: 
    x: -5.8058299648
    y: 0.165404601647
    z: 4.50232891986
  orientation: 
    x: 0.00249907606208
    y: 0.000708453209019
    z: 0.0138610026572
    w: -0.999900600617
```
```
header: 
  seq: 252486
  stamp: 
    secs: 633445690
    nsecs: 419158808
  frame_id: fcu
pose: 
  position: 
    x: -6.03800153732
    y: 0.445443034172
    z: 4.81723451614
  orientation: 
    x: 0.00267396630329
    y: 0.000531808934511
    z: 0.0139412081099
    w: -0.999899125477
```
I expect the copter to hold its position based on the pose estimated by vision. However, it stays still for about 3 seconds, then it shifts slightly, and then I see these messages:
```
WARN  [commander_tests] Failsafe enabled: no local position
INFO  [tone_alarm] fast_bat
WARN  [lib__ecl] EKF measurement timeout - stopping navigation
```
I have tried different publishing rates: 10hz, 20hz, and as the vision data come (~10-12 hz, the rate is not consistent but the estimated pose is always different). The result is always the same.
px4 version: 1.6.5
mavros version: 0.19.0
Ros Kinetic, Ubuntu 16.04 LTS

Am I doing anything wrong?
