### ISSUE TITLE
MAV_SYS_ID is only working if 1.

### ISSUE THREAD

**Issue by AlexisTM** [mavlink/mavros#872]
### Issue details

* If MAV_SYS_ID and tgt_system = 1: Everything works
* If MAV_SYS_ID and tgt_system = 82: Data flows yet the state stays not connected.
* Data flows means I receive data on topics `/mavros/local_position/local` or the imu
* State stays not connected means the topic `/mavros/state` reports `connected: False`

### MAVROS version and platform

Mavros: 0.21.3
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[x] PX4

Version: 1.6.5

### Launch file

For MAV_SYS_ID=82, tgt_system has been tested with 1, 82 and 0. All with same behaviour. 

```xml
<launch>
    <arg name="ROBOT_FULL_NAME" default="$(optenv ROBOT_FULL_NAME odroid00)" />

    <!-- vim: set ft=xml noet : -->
    <!-- base node launch file-->
    <arg name="fcu_url" default="/dev/ttyUSB0:921600" />
    <!--default="udp://@192.168.1.42" -->
    <arg name="gcs_url" default="" />
    <arg name="tgt_system" default="1" />
    <arg name="tgt_component" default="1" />
    <arg name="pluginlists_yaml" default="px4_pluginlists.yaml" />
    <arg name="config_yaml" default="px4_config.yaml" />
    <arg name="log_output" default="screen" />

    <node pkg="mavros" type="mavros_node" name="$(arg ROBOT_FULL_NAME)" required="true" output="$(arg log_output)">
        <param name="fcu_url" value="$(arg fcu_url)" />
        <param name="gcs_url" value="$(arg gcs_url)" />
        <param name="fcu_protocol" value="v2.0" />
        <param name="target_system_id" value="$(arg tgt_system)" />
        <param name="target_component_id" value="$(arg tgt_component)" />
        <!-- load blacklist, config -->
        <rosparam command="load" file="$(find ...)/cfg/$(arg pluginlists_yaml)" />
        <rosparam command="load" file="$(find ...)/cfg/$(arg config_yaml)" />
        <remap from="/tf" to="/$(arg ROBOT_FULL_NAME)/tf" />
        <remap from="/tf_static" to="/$(arg ROBOT_FULL_NAME)/tf_static" />
        <remap from="/mavlink/to" to="/$(arg ROBOT_FULL_NAME)/mavlink/to" />
        <remap from="/mavlink/from" to="/$(arg ROBOT_FULL_NAME)/mavlink/from" />
    </node>
</launch>
```

### Diagnostics

```
rostopic echo -n1 /diagnostics

header: 
  seq: 59
  stamp: 
    secs: 1455208301
    nsecs: 681187693
  frame_id: ''
status: 
  - 
    level: 1
    name: odroid82: FCU connection
    message: not connected
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Received packets:
        value: 52862
      - 
        key: Dropped packets:
        value: 0
      - 
        key: Buffer overruns:
        value: 0
      - 
        key: Parse errors:
        value: 0
      - 
        key: Rx sequence number:
        value: 222
      - 
        key: Tx sequence number:
        value: 10
      - 
        key: Rx total bytes:
        value: 2261764
      - 
        key: Tx total bytes:
        value: 40108
      - 
        key: Rx speed:
        value: 23808.000000
      - 
        key: Tx speed:
        value: 570.000000
  - 
    level: 0
    name: odroid82: GPS
    message: 3D fix
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Satellites visible
        value: 9
      - 
        key: Fix type
        value: 3
      - 
        key: EPH (m)
        value: 1.02
      - 
        key: EPV (m)
        value: 2.07
  - 
    level: 2
    name: odroid82: Heartbeat
    message: No events recorded.
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Heartbeats since startup
        value: 0
      - 
        key: Frequency (Hz)
        value: 0.000000
      - 
        key: Vehicle type
        value: Generic micro air vehicle
      - 
        key: Autopilot type
        value: Generic autopilot
      - 
        key: Mode
        value: ''
      - 
        key: System status
        value: Uninit
  - 
    level: 0
    name: odroid82: System
    message: Normal
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Sensor present
        value: 0x00000000
      - 
        key: Sensor enabled
        value: 0x00000000
      - 
        key: Sensor helth
        value: 0x00000000
      - 
        key: CPU Load (%)
        value: 61.9
      - 
        key: Drop rate (%)
        value: 0.0
      - 
        key: Errors comm
        value: 0
      - 
        key: Errors count #1
        value: 0
      - 
        key: Errors count #2
        value: 0
      - 
        key: Errors count #3
        value: 0
      - 
        key: Errors count #4
        value: 0
  - 
    level: 0
    name: odroid82: Battery
    message: Normal
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Voltage
        value: 24.38
      - 
        key: Current
        value: 0.0
      - 
        key: Remaining
        value: 88.0
  - 
    level: 0
    name: odroid82: Time Sync
    message: Normal
    hardware_id: /dev/ttyUSB0:921600
    values: 
      - 
        key: Timesyncs since startup
        value: 91
      - 
        key: Frequency (Hz)
        value: 9.791079
      - 
        key: Last dt (ms)
        value: -4.602662
      - 
        key: Mean dt (ms)
        value: -0.096830
      - 
        key: Last system time (s)
        value: 237.806095000
      - 
        key: Time offset (s)
        value: 1455208063.785467863
---
```

### Check ID

```
rosrun mavros checkid

ERROR. I got 0 addresses, but not your target 0:1

---
Received 0 messages, from 0 addresses
sys:comp   list of messages
```
