### ISSUE TITLE
Offboard control not arming

### ISSUE THREAD

**Issue by SarahMars** [mavlink/mavros#886]
### Issue details
I followed this link [(https://dev.px4.io/en/ros/mavros_offboard.html)] and used exactly same code as here. It worked fine in the simulation, but with the actual copter it doesn't arm. It will keep showing me "Offboard enabled". In the simulation it's only displayed once and then moved onto "Vehicle armed". With an actual copter, eventually it will arm but it is switched to AUTO.LAND and OFFBOARD continuously.

### MAVROS version and platform

Mavros: 0.20.0
ROS: Lunar
Ubuntu: 16.04
### Autopilot type and version
[ ] ArduPilot
[x] PX4
Version: 1.6.2

Here is the result of `rosrun mavros offb_node`
```
[ INFO] [1513065237.705473527]: Offboard enabled
[ INFO] [1513065242.754505876]: Offboard enabled
[ INFO] [1513065247.804223358]: Offboard enabled
[ INFO] [1513065252.854399812]: Offboard enabled
[ INFO] [1513065257.905596186]: Offboard enabled
[ INFO] [1513065262.954086947]: Offboard enabled
[ INFO] [1513065278.009690786]: Offboard enabled
[ INFO] [1513065301.732780519]: Offboard enabled
[ INFO] [1513065320.177190688]: Offboard enabled
[ INFO] [1513065325.183543481]: Offboard enabled
[ INFO] [1513065330.230271946]: Offboard enabled
[ INFO] [1513065335.280053988]: Offboard enabled
```

Here is the result of ` rostopic echo /mavros/state`
```
header: 
  seq: 13
  stamp: 
    secs: 1513065217
    nsecs: 209551346
  frame_id: ''
connected: True
armed: False
guided: False
mode: "MANUAL"
system_status: 3
---
header: 
  seq: 14
  stamp: 
    secs: 1513065224
    nsecs: 121481688
  frame_id: ''
connected: True
armed: False
guided: False
mode: "MANUAL"
system_status: 3
---
header: 
  seq: 15
  stamp: 
    secs: 1513065226
    nsecs: 133732073
  frame_id: ''
connected: True
armed: False
guided: False
mode: "MANUAL"
system_status: 3
---
header: 
  seq: 16
  stamp: 
    secs: 1513065232
    nsecs: 656473756
  frame_id: ''
connected: True
armed: False
guided: False
mode: "MANUAL"
system_status: 3
---
header: 
  seq: 17
  stamp: 
    secs: 1513065240
    nsecs: 595832083
  frame_id: ''
connected: True
armed: False
guided: False
mode: "MANUAL"
system_status: 3
---
header: 
  seq: 18
  stamp: 
    secs: 1513065243
    nsecs: 725434735
  frame_id: ''
connected: True
armed: False
guided: False
mode: "MANUAL"
system_status: 3
---
header: 
  seq: 19
  stamp: 
    secs: 1513065245
    nsecs: 712518297
  frame_id: ''
connected: True
armed: False
guided: False
mode: "MANUAL"
system_status: 3
---
header: 
  seq: 20
  stamp: 
    secs: 1513065247
    nsecs: 696344914
  frame_id: ''
connected: True
armed: False
guided: False
mode: "MANUAL"
system_status: 3
---
header: 
  seq: 21
  stamp: 
    secs: 1513065249
    nsecs: 680211985
  frame_id: ''
connected: True
armed: False
guided: False
mode: "MANUAL"
system_status: 3
---
header: 
  seq: 22
  stamp: 
    secs: 1513065259
    nsecs: 680977549
  frame_id: ''
connected: False
armed: False
guided: False
mode: ''
system_status: 0
---
header: 
  seq: 23
  stamp: 
    secs: 1513065262
    nsecs: 714840334
  frame_id: ''
connected: True
armed: False
guided: True
mode: "AUTO.LAND"
system_status: 3
---
header: 
  seq: 24
  stamp: 
    secs: 1513065264
    nsecs: 702423037
  frame_id: ''
connected: True
armed: False
guided: True
mode: "OFFBOARD"
system_status: 3
---
header: 
  seq: 25
  stamp: 
    secs: 1513065268
    nsecs: 702229789
  frame_id: ''
connected: True
armed: False
guided: True
mode: "OFFBOARD"
system_status: 3
---
header: 
  seq: 26
  stamp: 
    secs: 1513065270
    nsecs: 687947613
  frame_id: ''
connected: True
armed: False
guided: True
mode: "OFFBOARD"
system_status: 3
---
header: 
  seq: 27
  stamp: 
    secs: 1513065272
    nsecs: 673018690
  frame_id: ''
connected: True
armed: False
guided: True
mode: "AUTO.LAND"
system_status: 3
---
header: 
  seq: 28
  stamp: 
    secs: 1513065276
    nsecs: 507710218
  frame_id: ''
connected: True
armed: False
guided: True
mode: "AUTO.LAND"
system_status: 3
---
header: 
  seq: 29
  stamp: 
    secs: 1513065277
    nsecs: 495186702
  frame_id: ''
connected: True
armed: False
guided: True
mode: "AUTO.LAND"
system_status: 3
---
header: 
  seq: 30
  stamp: 
    secs: 1513065279
    nsecs: 161806859
  frame_id: ''
connected: True
armed: False
guided: True
mode: "AUTO.LAND"
system_status: 3
---
header: 
  seq: 31
  stamp: 
    secs: 1513065282
    nsecs: 568604580
  frame_id: ''
connected: True
armed: False
guided: True
mode: "OFFBOARD"
system_status: 3
---
header: 
  seq: 32
  stamp: 
    secs: 1513065285
    nsecs: 144734508
  frame_id: ''
connected: True
armed: False
guided: True
mode: "AUTO.LAND"
system_status: 3
---
header: 
  seq: 33
  stamp: 
    secs: 1513065288
    nsecs: 833649414
  frame_id: ''
connected: True
armed: False
guided: True
mode: "AUTO.LAND"
system_status: 3
---
header: 
  seq: 34
  stamp: 
    secs: 1513065289
    nsecs: 682942219
  frame_id: ''
connected: True
armed: False
guided: True
mode: "AUTO.LAND"
system_status: 3
---
header: 
  seq: 35
  stamp: 
    secs: 1513065299
    nsecs: 683815292
  frame_id: ''
connected: False
armed: False
guided: False
mode: ''
system_status: 0
---
header: 
  seq: 36
  stamp: 
    secs: 1513065300
    nsecs: 172258456
  frame_id: ''
connected: True
armed: True
guided: True
mode: "AUTO.LAND"
system_status: 4
---
header: 
  seq: 37
  stamp: 
    secs: 1513065302
    nsecs: 725203690
  frame_id: ''
connected: True
armed: True
guided: True
mode: "OFFBOARD"
system_status: 4
---
header: 
  seq: 38
  stamp: 
    secs: 1513065304
    nsecs: 711284531
  frame_id: ''
connected: True
armed: True
guided: True
mode: "OFFBOARD"
system_status: 4
---
header: 
  seq: 39
  stamp: 
    secs: 1513065308
    nsecs: 686127533
  frame_id: ''
connected: True
armed: True
guided: True
mode: "OFFBOARD"
system_status: 4
---
header: 
  seq: 40
  stamp: 
    secs: 1513065319
    nsecs: 626808003
  frame_id: ''
connected: True
armed: True
guided: True
mode: "AUTO.LAND"
system_status: 4
---
header: 
  seq: 41
  stamp: 
    secs: 1513065320
    nsecs: 844006906
  frame_id: ''
connected: True
armed: True
guided: True
mode: "AUTO.LAND"
system_status: 4
---
header: 
  seq: 42
  stamp: 
    secs: 1513065323
    nsecs: 715955948
  frame_id: ''
connected: True
armed: True
guided: True
mode: "AUTO.LAND"
system_status: 4
---
header: 
  seq: 43
  stamp: 
    secs: 1513065327
    nsecs: 684572636
  frame_id: ''
connected: True
armed: True
guided: True
mode: "AUTO.LAND"
system_status: 4

```

###Diagnostics
```
header: 
  seq: 59
  stamp: 
    secs: 1513065188
    nsecs: 195612994
  frame_id: ''
status: 
  - 
    level: 0
    name: "mavros: FCU connection"
    message: "connected"
    hardware_id: "/dev/ttyUSB0:57600"
    values: 
      - 
        key: "Received packets:"
        value: "18"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "120"
      - 
        key: "Tx sequence number:"
        value: "153"
      - 
        key: "Rx total bytes:"
        value: "1124"
      - 
        key: "Tx total bytes:"
        value: "9488"
      - 
        key: "Rx speed:"
        value: "552.000000"
      - 
        key: "Tx speed:"
        value: "318.000000"
  - 
    level: 2
    name: "mavros: GPS"
    message: "No satellites"
    hardware_id: "/dev/ttyUSB0:57600"
    values: 
      - 
        key: "Satellites visible"
        value: "0"
      - 
        key: "Fix type"
        value: "0"
      - 
        key: "EPH (m)"
        value: "Unknown"
      - 
        key: "EPV (m)"
        value: "Unknown"
  - 
    level: 1
    name: "mavros: Heartbeat"
    message: "Frequency too low."
    hardware_id: "/dev/ttyUSB0:57600"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "1"
      - 
        key: "Frequency (Hz)"
        value: "0.080004"
      - 
        key: "Vehicle type"
        value: "Quadrotor"
      - 
        key: "Autopilot type"
        value: "PX4 Autopilot"
      - 
        key: "Mode"
        value: "MANUAL"
      - 
        key: "System status"
        value: "Standby"
  - 
    level: 0
    name: "mavros: System"
    message: "Normal"
    hardware_id: "/dev/ttyUSB0:57600"
    values: 
      - 
        key: "Sensor present"
        value: "0x00000040"
      - 
        key: "Sensor enabled"
        value: "0x00000040"
      - 
        key: "Sensor helth"
        value: "0x00000040"
      - 
        key: "optical flow"
        value: "Ok"
      - 
        key: "CPU Load (%)"
        value: "49.7"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 0
    name: "mavros: Battery"
    message: "Normal"
    hardware_id: "/dev/ttyUSB0:57600"
    values: 
      - 
        key: "Voltage"
        value: "11.56"
      - 
        key: "Current"
        value: "0.3"
      - 
        key: "Remaining"
        value: "69.0"
  - 
    level: 2
    name: "mavros: Time Sync"
    message: "No events recorded."
    hardware_id: "/dev/ttyUSB0:57600"
    values: 
      - 
        key: "Timesyncs since startup"
        value: "0"
      - 
        key: "Frequency (Hz)"
        value: "0.000000"
      - 
        key: "Last dt (ms)"
        value: "0.000000"
      - 
        key: "Mean dt (ms)"
        value: "0.000000"
      - 
        key: "Last system time (s)"
        value: "0.000000000"
      - 
        key: "Time offset (s)"
        value: "0.000000000"
```
Thank you so much in advance.
