### ISSUE TITLE
How to use fake_gps plugin?

### ISSUE THREAD

**Issue by lajoiepy** [mavlink/mavros#917]
### Issue details

Hi!
I am looking into using the fake_gps plugin in mavros_extras to fly indoor. I have access to vision data in the form of a transform between frames called vision_origin and vision_pose_estimate.
Here's my config:
```
# fake_gps
fake_gps:
  # select data source
  use_mocap: false         # ~mocap/pose
  mocap_transform: false   # ~mocap/tf instead of pose
  use_vision: false       # ~vision (pose)
  # origin (default: Zürich)
  geo_origin:
    lat: 47.3667          # latitude [degrees]
    lon: 8.5500           # longitude [degrees]
    alt: 408.0            # altitude (height over the WGS-84 ellipsoid) [meters]
  eph: 2.0
  epv: 2.0
  satellites_visible: 5   # virtual number of visible satellites
  fix_type: 3             # type of GPS fix (default: 3D)
  tf:
    listen: true
    send: false           # send TF?
    frame_id: "vision_origin"       # TF frame_id
    child_frame_id: "vision_pose_estimate" # TF child_frame_id
    rate_limit: 10.0      # TF rate
  gps_rate: 5.0           # GPS data publishing rate
```
The plugin seems to work fine, but I am a little confused about the output I should expect. Nothing is published on /mavros/global_position/local nor on the other global_position topics.
Note that I am using PX4 with LPE and that I have set the `MAV_USEHILGPS` to `enabled` and `LPE_FUSION` to `1` (only GPS).

### MAVROS version and platform

Mavros: 0.21.2
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

PX4
Version: 1.6.3
