### ISSUE TITLE
Using mavros to connect with pixracer over wifi via udp 

### ISSUE THREAD

**Issue by jannsta1** [mavlink/mavros#998]
### Issue details

I am trying to connect to a pixracer unit with mavros. Previously I have used a companion computer that connects to pixhawk via a physical serial cable. Now I wish to use a wifi connection to communicate directly with pixracer via the ESP8266 board. I have configured the wifi which runs in station mode and happily connects with qGroundcontrol and my router (so I think the pixracer/ESP8266 are functioning and setup correctly) but I'm struggling to connect through mavros to the fcu. 

The udp address I'm using is: ```udp://:14557@192.168.1.9:14540```  - where 192.168.1.9 is the ip address of the pixracer

Does this format look OK? Perhaps there are some parameters I need to set too? I've set ```SYS_COMPANION``` to ```ESP8266 (921600 baud, 8N1)```. 

### MAVROS version and platform

Mavros: 0.22.0
ROS: Kinetic
Ubuntu: 16.04
### Autopilot type and version

[  ] ArduPilot
[x] PX4

Version: 1.6.5

### Node logs

```
copy output of mavros_node. Usually console where you run roslaunch
```

### Diagnostics

```
header: 
  seq: 15
  stamp: 
    secs: 1523479866
    nsecs: 896584974
  frame_id: ''
status: 
  - 
    level: 1
    name: "UAV_1/mavros: FCU connection"
    message: "not connected"
    hardware_id: "udp://:14557@192.168.1.9:14540"
    values: 
      - 
        key: "Received packets:"
        value: "0"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "0"
      - 
        key: "Tx sequence number:"
        value: "141"
      - 
        key: "Rx total bytes:"
        value: "0"
      - 
        key: "Tx total bytes:"
        value: "36947"
      - 
        key: "Rx speed:"
        value: "0.000000"
      - 
        key: "Tx speed:"
        value: "9547.000000"
  - 
    level: 2
    name: "UAV_1/mavros: GPS"
    message: "No satellites"
    hardware_id: "udp://:14557@192.168.1.9:14540"
    values: 
      - 
        key: "Satellites visible"
        value: "0"
      - 
        key: "Fix type"
        value: "0"
      - 
        key: "EPH (m)"
        value: "Unknown"
      - 
        key: "EPV (m)"
        value: "Unknown"
  - 
    level: 2
    name: "UAV_1/mavros: Heartbeat"
    message: "No events recorded."
    hardware_id: "udp://:14557@192.168.1.9:14540"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "0"
      - 
        key: "Frequency (Hz)"
        value: "0.000000"
      - 
        key: "Vehicle type"
        value: "Generic micro air vehicle"
      - 
        key: "Autopilot type"
        value: "Generic autopilot"
      - 
        key: "Mode"
        value: ''
      - 
        key: "System status"
        value: "Uninit"
  - 
    level: 0
    name: "UAV_1/mavros: System"
    message: "Normal"
    hardware_id: "udp://:14557@192.168.1.9:14540"
    values: 
      - 
        key: "Sensor present"
        value: "0x00000000"
      - 
        key: "Sensor enabled"
        value: "0x00000000"
      - 
        key: "Sensor helth"
        value: "0x00000000"
      - 
        key: "CPU Load (%)"
        value: "0.0"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 2
    name: "UAV_1/mavros: Battery"
    message: "No data"
    hardware_id: "udp://:14557@192.168.1.9:14540"
    values: 
      - 
        key: "Voltage"
        value: "-1.00"
      - 
        key: "Current"
        value: "0.0"
      - 
        key: "Remaining"
        value: "0.0"
  - 
    level: 2
    name: "UAV_1/mavros: Time Sync"
    message: "No events recorded."
    hardware_id: "udp://:14557@192.168.1.9:14540"
    values: 
      - 
        key: "Timesyncs since startup"
        value: "0"
      - 
        key: "Frequency (Hz)"
        value: "0.000000"
      - 
        key: "Last dt (ms)"
        value: "0.000000"
      - 
        key: "Mean dt (ms)"
        value: "0.000000"
      - 
        key: "Last system time (s)"
        value: "0.000000000"
      - 
        key: "Time offset (s)"
        value: "0.000000000"
---

```

### Check ID

```
ERROR. I got 0 addresses, but not your target 1:1
```
